### ISSUE TITLE
Does this plugin support script completion?

### ISSUE THREAD

**Issue by henghengyang** [AnWeber/vscode-httpyac#100]
```
### @name example
GET example.org
?foo=value

{{
console.info(response.parsedBody.data.length)
}}
```
when i type response key word, there is no code hinting

**Comment by AnWeber** [comment]
Code completion for Javascript I have not currently implemented. The implementation means several changes, for which I currently do not find the time. One would have to change the connection from httpyac to VSCode to [LSP](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide). From then on you could include the CodeCompletion similar to [vetur](https://github.com/vuejs/vetur/tree/master/server). This would also allow formatting, .... 
As a workaround I would recommend to simply import the javascript using `require`, then it is possible to achieve code completion using type hints (`npm i httpyac` needed). 

```http
### @name example
GET example.org
?foo=value

{{
require('script.js`)(response);
}}
```

```js
module.exports = function (/**@type {import('httpyac').HttpResponse}*/ response) {
  console.info(response.parsedBody.data.length);
}
```
![image](https://user-images.githubusercontent.com/13434739/150966346-fbace8ca-f5ec-4212-910e-75564ccb7ce2.png)

**Comment by henghengyang** [comment]
Okay，thank you for replay😃
I like this plugin,this is what I’m looking for.
I used IntelliJ http client then rest client,but both them can't satisfy me.

There are still some small details that need to be improved like what I have mentioned

**Comment by AnWeber** [comment]
The change is not small:-) But yes, you can still improve quite a bit. If you are interested, I am open to PR, but this change would be rather advanced. But there are still some more construction sites, which I want to attack (RabbitMQ, Debugging Adapter, ...)

**Comment by henghengyang** [comment]
I really want to do it, but unfortunately I'm a back-end engineer.😭

Anyway, thank you for developing such a good plugin

**Comment by AnWeber** [comment]
:-) I thought so too for a long time. And there's a reason why the whole thing doesn't have a GUI, like maybe postman or hoppscotch:-)

**Comment by henghengyang** [comment]
GUI is not very useful.I’d rather test api from file by using ide, it’s more easily faster and freedom

**Comment by AnWeber** [comment]
I am closing the ticket to combine all the requirements related to the implementation of LSP into one issue (#101)
