### ISSUE TITLE
AGPL-3.0 License File shows Httpyac annotation?!

### ISSUE THREAD

**Issue by DrRuhe** [AnWeber/vscode-httpyac#102]
This is a weird one...

The `send|env: -` thing is visible in a AGPL License file.
![Screenshot_20220202_230012](https://user-images.githubusercontent.com/29500714/152244604-b82e8122-3e55-48bd-b5b3-dbaa1c3f748a.png)

Here is a zipped version of the License file:
[ISSUE.zip](https://github.com/AnWeber/vscode-httpyac/files/7990350/ISSUE.zip)

**Comment by AnWeber** [comment]
?? thx. Will test it tomorrow

**Comment by AnWeber** [comment]
Unfortunately just a normal programming error from me. I have integrated Markdown support in my extension to be able to execute HTTP code blocks in markdown directly. 

````md
# Lorem ipsum

```http
GET https://httpbin.org/json
```
````


I would have restricted it to only saved markdown files and assumed that the file extension is always `md`. But in this case the license file is also interpreted as Markdown (LanguageId). When checking for markdown I now additionally consider other common endings and additionally the LanguageId in VSCode.

**Comment by AnWeber** [comment]
Fixed with the current version v4.10.2
