### ISSUE TITLE
Use the Workspace Trust API

### ISSUE THREAD

**Issue by Zlitus** [AnWeber/vscode-httpyac#104]
Hello 👋

Recently, Visual Studio Code introduced a new security feature : **Workspace Trust API**.

If you think that's make sense, you can declare your extension to provide complete, partial or no support in untrusted workspaces using the `untrustedWorkspaces` capability in `package.json`.

The following example declares that the extension is supported completely in untrusted workspaces. In this case, the extension is enabled in untrusted workspaces.

```json
{
	"capabilities": {
		"untrustedWorkspaces": {
			"supported": true
		}
	}
}
```

The next example declares that the extension is not supported in untrusted workspaces. In this case, the extension is disabled in untrusted workspaces.

```json
{
	"capabilities": {
		"untrustedWorkspaces": {
			"supported": false
		}
	}
}
```

I think it would be very useful to make your extension compatible with Untrusted Workspace, except if you think that would cause security issues.

Thank you for your amazing work 👍

**Comment by AnWeber** [comment]
Thanks for the tip, but I currently relied on the default of VSCode. Including the Trusted Api has not made sense so far, as I rely on javascript execution in [too many places](https://github.com/AnWeber/httpyac/search?q=evalExpression). However, I am currently modularizing the plugins more to offer the VSCode Web Extensions interface. In the course of this I will re-evaluate it again.

**Comment by AnWeber** [comment]
I looked at it again and would have found the following places that need to be adjusted
- prevent execution of javascript
- prevent import of any file outside of workspace folder
- prevent import of *.proto files

I play with the idea to confirm the call of a URL via popup before each request. The complete url can be hidden from the user. Attack vector would be to first query a local web service and send the result to a bad web service. Do you have an opinion about this?

**Comment by AnWeber** [comment]
added support of workspace trust api in v5.1.0
