### ISSUE TITLE
Python notebook show httpyac error

### ISSUE THREAD

**Issue by li1234yun** [AnWeber/vscode-httpyac#106]
Hello,  @AnWeber 
When I open python notebook `*.ipynb` file to edit, show the error message:

![image](https://user-images.githubusercontent.com/26505658/156712574-ab234fa8-bb0f-4c15-8fdb-92019cec8fbf.png)

When I disable httpyac plugin, the message will be gone. Maybe this is a bug.

**Comment by AnWeber** [comment]
Can you give me a source code file to reproduce the error? I suspect that the Markdown parsing is to blame.

**Comment by li1234yun** [comment]
@AnWeber 👍

**Comment by AnWeber** [comment]
There is a fun workaround. Installing Httpbook should fix the error. Then a method from vscode-httpyac is overridden, which fixes the error. But with the next release it is directly in vscode-httpyac

**Comment by li1234yun** [comment]
@AnWeber 👍

**Comment by AnWeber** [comment]
fixed error with v5.1.0 (released today)
