### ISSUE TITLE
Extension for error handling

### ISSUE THREAD

**Issue by jakoss** [AnWeber/vscode-httpyac#11]
Is there a way to create an extension that could handle error code with some custom logic? My idea is to create extension that will refresh JWT token every time the 403 gets returned from api. But i'm not sure if that's even possible right now

**Comment by AnWeber** [comment]
in principle it is enough to add a script block after the request. if you want to outsource it to a script file you can also use require to load the function and then use it

```html

GET https://www.google.de

{{
  const vscode = require('vscode');
  vscode.window.showInformationMessage(`${httpRegion.request.url} = ${httpRegion.response.statusCode}`);
}}
```

**Comment by jakoss** [comment]
That requires adding in every request import or script. That's fine, but i was hoping for something like http interceptor, that will be completely transparent from the request perspective.

So i will just write `GET https://www.google.de` and the interceptor would run the request, handle 403, refresh token and then rerun the original request with new token. This way user will get new token in background and the request will be successful without him even noticing that.

I'm trying to reach fully automated authorization process since i'm working on a project that will be run by more than 10 people in team. I would like to avoid any global scripts or imports if possible

**Comment by AnWeber** [comment]
It would be similar to [DigestAuthVariableReplacer](https://github.com/AnWeber/httpyac/blob/master/src/variables/replacer/digestAuthVariableReplacer.ts)

Set `httpyac.extensionScript` to valid nodejs script like
```js

//(text: string, type: VariableReplacerType | string, context: ProcessorContext) => Promise<string | undefined>;
function tokenRefreshFunction(text, type){
  if(type === 'Url'){
  ...
  }
  return text;
}
const {httpYacApi} = require('httpYac');
httpYacApi.variableReplacers.push(tokenRefreshFunction);
```
I try not to break the api but no guarantee.

**Comment by AnWeber** [comment]
If you need further help, just get in touch.

**Comment by jakoss** [comment]
I'm struggling to register the extension script. I have such directory structure
![image](https://user-images.githubusercontent.com/3933348/108511438-339ac380-72c0-11eb-8e74-5628acbe8157.png)

I tried `"httpyac.extensionScript": "./extensions/httpyac_extension.js"` or `"httpyac.extensionScript": "../extensions/httpyac_extension.js"` but nothing works. The script seems to be completely ignored

**Comment by AnWeber** [comment]
It was more or less a mistake of mine to allow it relative to the workspace. The script registers globally in my extension and is used in all workspaces. For this reason I will only allow an absolute path in the future.
Probably the error in your case is that the script is only executed when the extension is activated. If you have already started another VS Code instance, or if you have created the script afterwards, it would not be executed. 
My intention with the extension script was a one-time execution of the script for the registration of additional parsers. I'm thinking about offering another script injection point, which gets executed on every request call.

**Comment by jakoss** [comment]
Absolute path is not really a solution for me since i'm trying to create shared workspace in git repository.

Injection point for every request call seems to be a better solution. It will be very cumbersome to create extension if i need to start a new vscode instance all the time

**Comment by AnWeber** [comment]
I added support for script injection per httpRegion. Just give me a hint if you experience problems.

**Comment by jakoss** [comment]
Hmm it's loaded once, but after i do any change in the script i have to reload whole vscode to see that change working. That make developing extension quite tedious, but at least the relative path to `httpRegionScript` works fine. I can work with current version, but automatic reloading of script for every request would be a lifechanger :)

**Comment by AnWeber** [comment]
In principle, you could simply load another script file from the script using require, on each call to the parser/variableReplacer (which you implement).
You might have to invalidate the [require.cache](https://stackoverflow.com/questions/9210542/node-js-require-cache-possible-to-invalidate) though. But I have not tried it yet.

```js
//(text: string, type: VariableReplacerType | string, context: ProcessorContext) => Promise<string | undefined>;
function tokenRefreshFunction(text, type){
  if(type === 'Url'){
    delete require.cache[require.resolve('./reloadOnEveryCall.js')]
    require(`./reloadOnEveryCall.js')(text, type);
  }
  return text;
}
const {httpYacApi} = require('httpYac');
httpYacApi.variableReplacers.push(tokenRefreshFunction);
```
Calling the script several times is relatively difficult, because it registers your logic several times. If there is no other way, I can consider to offer a debug setting where you nod off this error

**Comment by jakoss** [comment]
I'll try to work with that for now
