### ISSUE TITLE
References to not open documents are not kept in memory after evaluation

### ISSUE THREAD

**Issue by fredrikhr** [AnWeber/vscode-httpyac#112]
If a region references a region in another file that is not currently open, a normal `@ref` reference is evaluated as if it were a `@forceRef`. Multiple repeated executions of the region trigger the `@ref` evaluation each time. However, if I open the file in which the referenced region is located, the first evaluation is stored in memory, and subsequent calls use the stored value instead of re-evaluating.

It should not matter whether a file is opened or not. A reference should only be evaluated on first call, subsequent calls should use the stored value.

**Comment by AnWeber** [comment]
I have reverted the changes to the ImportMetaDataHandler from v5.2.0 and it also saves unopened files as before. With v5.2.1 it works again.
