### ISSUE TITLE
grpc support tls

### ISSUE THREAD

**Issue by akkuman** [AnWeber/vscode-httpyac#115]
In the current documentation, I can't find how to set TLS

**Comment by AnWeber** [comment]
I have added an example with SSL [here](https://github.com/httpyac/httpyac.github.io/blob/main/examples/request/grpc/grpcSSL.http). Internally I use [@grpc/grpc-js](https://github.com/grpc/grpc-node/tree/master/packages/grpc-js) to access GRPC Services. See https://grpc.github.io/grpc/node/grpc.credentials.html for Documentation how to create ChannelCredentials

```
proto < ./hello.proto

{{@request
const grpc = require('@grpc/grpc-js'); //require grpc-js used by httpyac
request.headers.channelcredentials = grpc.ChannelCredentials.createSsl();
}}
GRPC grpcb.in:9001/hello.HelloService/sayHello
{
  "greeting": "world"
}
```

**Comment by asinitson** [comment]
Trying the example from the message above and it is not working:
![image](https://user-images.githubusercontent.com/13285303/226325160-eb2c7689-17f1-4c5d-a677-895e6d225db5.png)

The same without TLS works fine:
![image](https://user-images.githubusercontent.com/13285303/226325425-fa529f2f-9c87-46ed-90a2-e2a08f7054e5.png)

Should I open the new issue for this? Not sure how to get any more information besides what is shown on screenshot. Info about VSCode:
```
Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:26.920Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.14.21-150400.24.46-default
Sandboxed: No
```

**Comment by AnWeber** [comment]
@asinitson I will take a look.
