### ISSUE TITLE
Titles no longer show up in outline

### ISSUE THREAD

**Issue by asherber** [AnWeber/vscode-httpyac#117]
Using 5.2.2 with a document with multiple requests, the request titles no longer show up in the outline view (outline view is empty).

```
### Foo
GET https://foo.com

### Bar
GET https://bar.com
```

**Comment by AnWeber** [comment]
@asherber I am not sure what is meant. The display in the Outline View still looks correct to me.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/13434739/160192327-bfa4dd3e-c50b-4430-9cd3-557a34b0123f.png">

**Comment by asherber** [comment]
Interesting -- this was not working for me yesterday, but it is today, with the same files!
