### ISSUE TITLE
BUG: reponse suffix missing when path contains array variable

### ISSUE THREAD

**Issue by rngtng** [AnWeber/vscode-httpyac#118]
Somehow the response is missing syntax highlighting although the content-header is `content-type: application/json`.

```
GET /foo/{{response.items[0].id}}
```

I see in the table the filename is missing `.json` suffix. But this it's working:

```
GET /foo/1
```

I this related due to the variable in path?

**Comment by rngtng** [comment]
Ah this works too:
```
@id = item.id
GET /foo/{{id}}
```

so maybe related to object chains in variable

**Comment by AnWeber** [comment]
Actually, no. Probably rather my regex has struck, which tries to recognize file extensions at the URL. However, I would have thought that I had a fix for this in the last version (https://github.com/AnWeber/vscode-httpyac/commit/a546aeaa8fe914ccc226177c27b04db2f73ab18a). Will test it.

**Comment by rngtng** [comment]
hm, I can't reproduce it anymore. maybe I was on an old version... 
closing

**Comment by AnWeber** [comment]
thx for closing
