### ISSUE TITLE
Dynamic disabling behavior inconsistent or ignored

### ISSUE THREAD

**Issue by gerukin** [AnWeber/vscode-httpyac#119]
### Global script

Before execution:
<img width="296" alt="Screen Shot 2022-04-04 at 17 52 42" src="https://user-images.githubusercontent.com/36127103/161510479-98e063ec-ca3b-4949-bb0d-932215ad932c.png">

The `send` link is clickable and works normally, giving this:
<img width="912" alt="Screen Shot 2022-04-04 at 17 53 03" src="https://user-images.githubusercontent.com/36127103/161510631-e794ed1c-aa7a-47b7-98e1-a00d6a9998a2.png">

The `send` link never disappears.
Note: it does disappear fine when `@disabled` is used.

### Global pre-request script

Note: I reloaded the window after the above test.

Before execution:
<img width="298" alt="Screen Shot 2022-04-04 at 17 53 50" src="https://user-images.githubusercontent.com/36127103/161510811-6d73f547-aa98-4253-8d8f-962a66b4573b.png">

The `send` link is clickable and works normally, giving this:
<img width="908" alt="Screen Shot 2022-04-04 at 17 53 57" src="https://user-images.githubusercontent.com/36127103/161510889-5b2f1878-172a-4c64-83dc-3a5277d0e84d.png">

The `send` link does disappear at this point.

### Suggestions

I assume it would be difficult to handle fully dynamic versions of this scenario from the beginning as this might depend on running arbitrarily complex sync or async code or other requests... so I wouldn't expect the `send` link to be gone from the start. But clicking it should ideally not execute the request, based on the result of the variable at that time (it should also not remove the link afterwards, even if the result was `true` for the previous execution, as this might no longer be the case).

Also see this related [CLI issue](https://github.com/AnWeber/httpyac/issues/246).

**Comment by AnWeber** [comment]
> I assume it would be difficult to handle fully dynamic versions of this scenario

This is exactly the kind of scenario I want to avoid at all costs. For this reason, it does not make sense to disable the display of the CodeLens. I remove the code.
