### ISSUE TITLE
Variable in default header settings

### ISSUE THREAD

**Issue by jakoss** [AnWeber/vscode-httpyac#12]
I'd like to use default header in my workspace settings like that: `"Authorization": "Bearer {{access_token}}"`, but unfortunetely the variable isn't picked up here. Is there a way around that?

**Comment by AnWeber** [comment]
I'm sorry, but I couldn't follow it. In my example it currently works.

```html
GET https://www.google.de?q={{query}}
```

settings.json
```json
"httpyac.environmentVariables": {
  "$shared": {
    "query": "httpyac"
  }
}
```
possibly an error is issued in the outputchannel of httpyac. 
![test](https://user-images.githubusercontent.com/13434739/108033929-0981a100-7035-11eb-9ea8-27450046140c.gif)

**Comment by jakoss** [comment]
No no, i mean i want to use variable inside settings value. So i have environment variable {{access_token}} and i want it in settings like this: `"Authorization": "Bearer {{access_token}}"`. What i want to achieve is to have `Bearer <real_token_from_env_here>` when i read `Authorization` setting

**Comment by AnWeber** [comment]
good point. The default headers are added right before the request is sent. Variable Replacement was already executed there. You should currently use the headers per file. With these headers the variable replacment should happen. But I will improve it in a next release.

```html
{{
  exports.defaultHeaders = {
    'Content-Type': 'text/html',
    'Authorization': `Bearer ${token}`
  };
}}
GET https://www.google.de HTTP/1.1
...defaultHeaders
```

**Comment by jakoss** [comment]
Yes, that's what i'm doing right now, but i'd like to automate it to the point that new endpoints will be just url + body, nothing more required :)

**Comment by AnWeber** [comment]
I published a new release. Can you please verify the change

**Comment by jakoss** [comment]
Works perfectly, thanks!
