### ISSUE TITLE
Is there an simple way to 'filter' content of the responsePreview?

### ISSUE THREAD

**Issue by rngtng** [AnWeber/vscode-httpyac#121]
I wonder if there's a simple way to filter/manipulate the content of the responsePreview. Usecase is that I'm explorative testing an api and focus only on certain output. e.g. just one attribute of each object in an array list. In `jq` this would be 

```
curl -s https://httpbin.org/json | jq '.slideshow.slides | map({title: .title})'
```

Now I'd like to  archive similar in vscode. I've in mind something like this:

```
GET https://httpbin.org/anything

{{after
preview = JSON.stringify(response.slideshow.slides.map(o => {  return {title: o.title}}))
}}
```

Any ideas?

**Comment by AnWeber** [comment]
For this I would have provided the `@responseLogging` event. Before the event is executed, a copy of the response is created and modified. This response is then displayed. But this is not the response for the further execution. If this should be changed, that would be the `@response` event.
```
GET https://httpbin.org/json

{{@responseLogging
  response.headers = {foo: "bar"};
  delete response.rawBody;
  delete response.prettyPrintBody;
  response.body = JSON.stringify(response.parsedBody.slideshow.slides, null, 2);
  delete response.parsedBody;
}}
```

or
https://github.com/httpyac/httpyac.github.io/blob/main/examples/plugins/responseLoggingHook/httpyac-plugin-example/index.js#L2

**Comment by rngtng** [comment]
Thanks this works. In the end I go with

```
GET https://httpbin.org/json

{{@responseLogging
  response.prettyPrintBody = JSON.stringify(response.parsedBody.slideshow.slides, null, 2);
}}
```

**Comment by rngtng** [comment]
Tataaa. I thought I create a simple plugin out of this idea: Introducing [httpyac-plugin-jq](https://github.com/rngtng/httpyac-plugin-jq). With this plugin installed you can apply (any?) existing `jq` command. Woooot!? Example:

```
# @name example
# @jq .slideshow.slides | map({title: .title})
GET https://httpbin.org/json
```

Results in 

```json
[
  {
    "title": "Wake up to WonderWidgets!"
  },
  {
    "title": "Overview"
  }
]
```

THANKS TO https://github.com/sanack/node-jq

**Comment by rngtng** [comment]
btw @AnWeber figured the responseLogging rules are different between CLI and vscode. hence this super dirty hack here: https://github.com/rngtng/httpyac-plugin-jq/blob/main/src/index.js#L12-L19. Any idea how I better can detect if it's run in vscode, or even better how to align the responseLogging rules?

**Comment by AnWeber** [comment]
You have to be careful, depending on the setting, one of the other [bodies is also used in vscode.](https://github.com/AnWeber/vscode-httpyac/blob/main/src/view/editorResponseHandler.ts#L20-L33) (code in [CLI](https://github.com/AnWeber/httpyac/blob/main/src/utils/requestUtils.ts#L247). To better detect VSCode, I would either query on `process.env.VSCODE_NLS_CONFIG`. Alternative would be to check if `require('vscode')` returns an object, as this is only registered in vscode extension for script execution (https://github.com/AnWeber/vscode-httpyac/blob/main/src/io/javascriptProvider.ts#L4).

**Comment by rngtng** [comment]
Thanks. Well, best I’d need the condition at all. Need to investigate what’s the best setup is.

**Comment by rngtng** [comment]
Updated plugin to v0.2.2. Now I don't need the condition to decide between vscode/CLI anymore. I just followed your advice above, dunno why I didn't earlier ;). https://github.com/rngtng/httpyac-plugin-jq/blob/main/src/index.js#L12-L14
