### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by asherber** [AnWeber/vscode-httpyac#122]
Is there some way to turn on debug logging for this extension within VS Code? 

On more than one occasion, I have sent a request, and after the response comes back I can see in my http file all of the CodeLens text disappear. From that point on, it's like the extension isn't loaded -- even opening a new http file doesn't bring back CodeLens. The only way to restore things is to reload VS Code.

I'd like to be able to see what's happening at the point that the CodeLens text disappears.

This happens to me on more than one file. It never happened to me until a few days ago -- although it had been a while before that since I last used httpyac. This is what caused #117 -- after CodeLens disappears, opening a new http file doesn't show anything in the Outline view.

**Comment by asherber** [comment]
![](https://user-images.githubusercontent.com/5248041/162334557-4f86c6e9-4a16-4211-bf7d-543b56486c71.gif)

**Comment by asherber** [comment]
I think it has something to do with the response window. If I reload the workspace with the response window still open, the CodeLens hints do not reappear. If I close the response window and then reload, CodeLens comes back.

Here are my httpyac settings:

```
    "httpyac.environmentPickMany": false,
    "httpyac.environmentShowStatusBarItem": true,
    "httpyac.responseViewExtensionRecognition": "mimetype",
    "httpyac.responseViewLanguageMap": {
        "application/json": "json",
        "application/soap+xml": "xml",
        "text/html": "html",
        "text/xml": "xml"
    },
    "httpyac.responseViewMode": "preview",
    "httpyac.useDecorationProvider": false,
```

**Comment by AnWeber** [comment]
I had this behavior only when an error occurred in the extension while debugging. But I haven't found out yet why the whole extension dies. In the settings I have a setting `httpyac.logLevel`, but whether that helps I can not say. For the logging an output channel `httpyac (log)` is created. In this channel also errors would be logged. I'll take the configuration once, and test it against my services.

**Comment by asherber** [comment]
Thanks, Dev Tools was a good suggestion. It showed me an error that was coming up in another extension ([XML Tools](https://marketplace.visualstudio.com/items?itemName=qub.qub-xml-vscode)) when the response was XML, and then I noticed that I was seeing this issue on all my requests with XML responses, but not those with JSON responses. I disabled the XML Tools extension, which hasn't been updated since 2017, and the issue went away.

I was able to reproduce this in a workspace with only httpyac and XML Tools, without any of my custom httpyac settings, using the dummy API endpoint [http://restapi.adequateshop.com/api/Traveler?page=1](http://restapi.adequateshop.com/api/Traveler?page=1)  With XML Tools disabled, the payload comes back fine; with XML Tools on, the above behavior is exhibited (XML Tools error, httpyac dies).

@AnWeber I'm not sure whether there's some way for httpyac to protect itself against external errors like this.

For anyone else reading this thread, please note that this is the XML Tools extension by Qub, not the more common one by Josh Johnson. I have the Josh Johnson one installed as well -- not sure when or why I added the Qub one.

**Comment by AnWeber** [comment]
The extension cannot secure itself. All VScode extensions run in the so-called extension host and VSVode would have to build a sandbox. But VScode offers an API that extensions can communicate directly with each other, so I don't think this will be implemented. 

Glad to see that it works again. :-)
