### ISSUE TITLE
How to save to a file in current working directory?

### ISSUE THREAD

**Issue by rngtng** [AnWeber/vscode-httpyac#129]
I try to store parts of a response to a file in the current working directory of VScode. But it always ends up in the httpyac execution directory. Any ideas how to point to right directory? I guess, I need to access the custom file store, but how? 

### Example code:

```
### Store http method value to file
# @name test
GET https://httpbin.org/anything

{{
  const fs = require('fs');
  fs.writeFileSync("foo.txt", `method=${test.method}`)
}}
```

### Expectation
file `foo.txt` is written with content `method=GET`.

**Comment by AnWeber** [comment]
just use `__dirname`

```
### Store http method value to file
# @name test
GET https://httpbin.org/anything

{{
  const fs = require('fs');
  fs.writeFileSync(`${__dirname}/foo.txt`, `method=${test.method}`)
}}
