### ISSUE TITLE
Parsed jwt token not available in script after request

### ISSUE THREAD

**Issue by jakoss** [AnWeber/vscode-httpyac#13]
I'm trying to access parsed token in script after request like this: 
```
# @name login
# @jwt AccessToken
POST /login

{
    "Login": "{{user}}",
    "Password": "{{password}}"
}

{{
    const vscode = require('vscode');
    vscode.window.showInformationMessage("token: " + login.AccessToken_parsed)
}}
```

But the login.AccessToken_parsed is undefined in script. In response preview the token is properly parsed

**Comment by AnWeber** [comment]
Is your response of content type application/json? All response are returned as string. Only if it is a JSON Mimetype it gets [parsed](https://github.com/AnWeber/httpyac/blob/3eae73bcdeb00374d7c87b5e8f5e3d8c88d49ff9/src/actionProcessor/httpClientActionProcessor.ts#L36-L54)

In my example it seems to work:
```
# @name login
POST https://httpbin.org/post

{
 "user": "foo",
 "password": "bar"
}

content

{{
  log.info(login.data);
}}
```
![response_json](https://user-images.githubusercontent.com/13434739/108081284-13c19080-7071-11eb-810f-417798f5d2ff.gif)

**Comment by jakoss** [comment]
All other fields are available and properly set. Only the parsed jwt token isn't there

**Comment by AnWeber** [comment]
The order of execution has not been correct. The following sequence was generated by the parser logic: request => js => jwt. I changed priority of jwtActionProcessor.

**Comment by AnWeber** [comment]
I have provided a new version in which the error should be fixed (v1.12)

**Comment by jakoss** [comment]
Unfortunetely the `_parsed` field is still undefined in the script after request

**Comment by AnWeber** [comment]
Unfortunately true. But there is a workaround. Just parse the token yourself
```
const {utils}= require('httpYac');
const parsedAccess_token = utils.decodeJWT(login.access_token);
```

**Comment by jakoss** [comment]
That works for me, thanks again

**Comment by AnWeber** [comment]
I'm fixing it anyway, as I find the use case interesting. Thanks for testing my extension.
By the way, you can always use any extensions from the npm registry. You are not limited to my helper methods. And it is possible to debug into the script of the *.http files. When I test my extension, I can also debug into the script and look at the variables.

**Comment by jakoss** [comment]
How do you debug script? Because i cannot leave a breakpoint in *.http file

**Comment by AnWeber** [comment]
1. unzip [debug.zip](https://github.com/AnWeber/vscode-httpyac/files/5996723/debug.zip)
2. open with code and start debugging (a new instanace of vscode is starting)
3. open your project/*http file
4. add debugger; to your script
```
{{
debugger;
log.info('test');
}}
```

![debug](https://user-images.githubusercontent.com/13434739/108228162-e3482800-713e-11eb-89bd-a559ead2fd5c.gif)

**Comment by jakoss** [comment]
Kinda complicated but works fine :)
