### ISSUE TITLE
Copy exported variable content

### ISSUE THREAD

**Issue by bugybunny** [AnWeber/vscode-httpyac#131]
(not sure if exported variable is the correct term)
In this view I would like to be able to copy the content of exported variables
![image](https://user-images.githubusercontent.com/5311105/173045531-810eda36-9534-45f9-9d21-e8bcbf5820fe.png)

This seems impossible as of now. I would suggest a right click > copy.

**Comment by AnWeber** [comment]
This seems to be more of a bug. I have already [implemented it](https://github.com/AnWeber/vscode-httpyac/blob/main/src/provider/objectTreeItem.ts#L35-L39), but it seems to work correctly only for string values.
