### ISSUE TITLE
Preventing variable evaluation

### ISSUE THREAD

**Issue by sir-farfan** [AnWeber/vscode-httpyac#134]
With the breaking change from 5.3.0 (2022-04-03) the following request stopped working:
```
PATCH http://my.service.com/template/1

{ "body": "Hello {{useremail}}" }
```

It's trying to evaluate the string {{useremail}} as a variable, which isn't defined.
When I tried defining `@useremail="{{useremail}}"`, it got in an infinite loop which didn't end even after closing VSCode.

I need to send the string `"Hello {{useremail}}"` as is.
Is there a way to do it?

**Comment by AnWeber** [comment]
You could prevent variable evaluation using escape format (https://httpyac.github.io/guide/variables.html#variable-substitution-in-request)

```
POST https://httpbin.org/anything HTTP/1.1
{
  "template": "My \{\{someVerb\}\} template!!"
}
```

But I will change my code to preventan infinite loop.

**Comment by sir-farfan** [comment]
thanks
