### ISSUE TITLE
POST application/x-www-form-urlencoded and response handler script is broken

### ISSUE THREAD

**Issue by dypa** [AnWeber/vscode-httpyac#14]
Test case:
```
POST https://httpbin.org/anything
Content-Type: application/x-www-form-urlencoded
accept: application/json

email=user@domain.loc&password=pass

> {% client.global.set("email", response.body.form.email); %}
```

Actual result:
```
{
...
  "form": {
    "email": "user@domain.loc",
    "password": "pass\n\n> {% client.global.set(\"email\", response.body.form.email); %}"
  },
...
}
```

Expected result:
```
{
...
  "form": {
    "email": "user@domain.loc",
    "password": "pass"
  },
...
}
```

**Comment by AnWeber** [comment]
currently I expect the following format. I need to adjust [regex](https://github.com/AnWeber/httpyac/blob/main/src/parser/intellijHttpRegionParser.ts#L13). Is this notation valid in Intellij?

```
> {%
client.global.set("email", response.body.form.email);
%}

**Comment by dypa** [comment]
spec:
* https://github.com/JetBrains/http-request-in-editor-spec/blob/master/spec.md#324-response-handler

more examples:
* https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html#using-response-handler-scripts
* https://www.jetbrains.com/help/idea/http-response-handling-examples.html


valid syntax: 
1. `> {% %}`
2. 
```
> {%

%}
```
3. `> scripts/my-script.js`

invalid syntax:
* two and more spaces between > and {. example `>  {% %}`
* space between { and %. example  `> { %`
* two and more response handler script in one request.

**Comment by AnWeber** [comment]
The two commits should have fixed the bug already. But I still saw a discrepancy in [parsing the url]( https://github.com/JetBrains/http-request-in-editor-spec/blob/master/spec.md#3213-resource-path) when reading the spec, which I also want to incorporate before the next release.

**Comment by AnWeber** [comment]
new version with fix is released. may you please test. thanks:-)

**Comment by dypa** [comment]
build: 1.16.0
my tests passed.
