### ISSUE TITLE
Wrong test result written to UI

### ISSUE THREAD

**Issue by BramManuel** [AnWeber/vscode-httpyac#143]
If I run a test with two test results where the second test fails, the success message from the first test is written as the error message.
![image](https://user-images.githubusercontent.com/27723033/183022326-bec52210-ad19-4db5-8b52-54433683dccc.png)

When you click here:
![image](https://user-images.githubusercontent.com/27723033/183022837-350f9b87-4097-46d9-b66c-cf177c615347.png)

Then you see that the second statement failed.
![image](https://user-images.githubusercontent.com/27723033/183022356-10597c22-6867-49ed-8b75-518a78ba1e01.png)

**Comment by AnWeber** [comment]
only successful messages were output by mistake. I have now reversed the condition and corrected it. Thanks
