### ISSUE TITLE
@import should trim the file name

### ISSUE THREAD

**Issue by bugybunny** [AnWeber/vscode-httpyac#150]
If a line with `@import` contains a space after the file name the file is not found
![image](https://user-images.githubusercontent.com/5311105/190417309-4d47f081-34b6-48de-ac26-877d700a7ff3.png)
because it searches for "../myfile.http " literally. A trim would be nice because those spaces are hard to see — and not recognizable in the error message — and it seems counterintuitive to include them if I am not missing a good reason to really include the space(s) in the lookup for the file.

If it's on purpose we should mention it in the docs https://httpyac.github.io/guide/variables.html#import-variables.

**Comment by AnWeber** [comment]
No, not intentional, but never fallen over it either. Probably because I have enabled `files.trimTrailingWhitespace`. I adjusted the parsing in this and a few other places.

**Comment by AnWeber** [comment]
released with v5.7.2
