### ISSUE TITLE
Multiline requests don't support protocol

### ISSUE THREAD

**Issue by hffmnn** [AnWeber/vscode-httpyac#159]
A request like

```
GET https://httpbin.org
  /get
```

sends a request to `https://httpbin.org/get` => ✅ 

---
Adding the protocol breaks the request:

```
GET https://httpbin.org
  /get HTTP/1.1
```

sends a request to `https://httpbin.org/get%20HTTP/1.1`

**Comment by AnWeber** [comment]
:-) yes, more or less a known issue. I was too lazy to implement it for every line.if you add the protocol in the first it will work. I will fix it.

**Comment by AnWeber** [comment]
I have fixed it. Just for info but specifying the protocol is not mandatory unless you want to make sure that the CLI (default v2) uses the same Http version as the extension in vscode (default 1.1)

**Comment by hffmnn** [comment]
Nice. Thanks a lot.
