### ISSUE TITLE
Extension for pm. sandbox

### ISSUE THREAD

**Issue by IntranetFactory** [AnWeber/vscode-httpyac#16]
We are currently prototyping a conversion of our PostMan collections to *.http files. We use a lot of pre-request and test scripts. In these scripts we especially use `pm.environment.*`  `pm.response.*` `pm.sendRequest`  `pm.visualizer` and, for various reasons, we would like to keep the scripts unmodified for now.  
   
We are wondering if it should be possible to implement an extension to provide a compatible pm object?   
   
Would you be interested to provide such a pm compatibility layer and/or to include it if we would provide it with a PR?

**Comment by AnWeber** [comment]
Providing a Postman interface is implementable. I have done the same with [Intellij HttpClient](https://github.com/AnWeber/httpyac/blob/e486b99c07e185763587f925bea7627c25a26da5/src/actionProcessor/intellijActionProcessor.ts#L98-L127) as well.
Only the implementation is much more difficult for Postman, because the methods are more powerful and have more dependencies. Time-wise, I will certainly not be able to do that at the moment.
You could implement it via pull request, but I would rather like the approach of a custom extension. My extension already exports an [interface](https://github.com/AnWeber/vscode-httpyac/blob/main/src/extension.ts#L82-L84) that could be used by this extension. Then you could add your own parser logic for Postman. Another approach would be to use the httpyac.extensionScript setting, which can achieve the same thing, but with more limited development.

**Comment by IntranetFactory** [comment]
We already developed a PM shim in the past. It's not a complete implementation, as it only covers our specific pm use cases. We will try if that might be a starting point to implement another shim. I currently assume that pm.environment.* pm.response.* should be fairly easy to implement when an extension can access the current environment and last response objects/state/model. 

`pm.sendRequest` is quite essential for us, and I'm not sure where to hook that up. The pre-/post-request scripts might contain multiple pm.sendRequest statements, which are then queued. The script block may not finish until all sendRequests are resolved. Do you have any idea where/how we could add such a queue and delay execution of the next section until all requests are resolved?

**Comment by AnWeber** [comment]
1. It should work analog to the Intellij implementation

- [envProvider](https://github.com/AnWeber/httpyac/blob/main/src/environments/intellijEnvProvider.ts):  provide variables from postman environment with postman.backup.json.This is optional if the environment variables are changed over
- [httpRegionParser](https://github.com/AnWeber/httpyac/blob/main/src/parser/intellijHttpRegionParser.ts): parse contents of file line by line. The parser adds an action to the region's processing queue (httpRegion.actions) and returns the end of the script scope.
- [actionProcessor](https://github.com/AnWeber/httpyac/blob/main/src/actionProcessor/intellijActionProcessor.ts): Here the shim must be created and passed as a variable to the executeScript. Only a rough sketch.
```js
// only mock
import executeScript from 'jsActionProcessor'

export async function postmanActionProcessor(scriptData: ScriptData | IntellijScriptData, context: ProcessorContext) {
	const requests = [];
	const pm = {
		enviroment = context.variables,
		response = context.httpRegion.response,
		sendRequest:  (request, callback) => requests.push({requuest, callback)
	}
	
	await executeScript(scriptData.script, context.httpFile.filename, { pm }, scriptData.lineOffset)
	
	while(obj = request.pop()){
		const response = await httpClient(obj.request, context);
		callback(response)
	}

return true; //on false queue is cancelled
}
```

2. You may not even need your own parser if you outsource the creation of the shim to a script.
```html
{{
const pm = require('./postman-shim.js)(httpRegion.response, this);//this to get all global variables

// postman code

exports.pending = pm.close() // loop all requests, promise must get exported, to make [jsActionProcssor wait](https://github.com/AnWeber/httpyac/blob/main/src/actionProcessor/jsActionProcessor.ts#L101)
}}
```

Option 1 is working, Option 2 should work and would be much easier to implement.

But for me, the question is rather whether you can not convert the code relatively easily using search and replace in a valid NodeJS. Shim approach would only make sense for me from > 5000 lines of code.

**Comment by AnWeber** [comment]
I briefly tested option 2. In principle, this also works. I would recommend that

**Comment by IntranetFactory** [comment]
We have a lot of code, and we have a shim executing that code embedded into our product. So currently being able to reuse the code unchanged is essential for us. Implementing another shim is a lot less work for us right now.

Option 2 sounds great - would it be possible to have a global require for all files in a workspace?  So that all files could use pm. ?

**Comment by AnWeber** [comment]
Just include one global script per file or use setting httpyac.httpRegionScript. But It will not work, because in every script you need a exports.pending = pm.close(). You need to export your promise.
If you want it general then option 1 is better suited.

**Comment by AnWeber** [comment]
Closing the Issue. If you have any questions just contact me again.
