### ISSUE TITLE
support GraphQL request syntax of IntelliJ IDEA HTTP client

### ISSUE THREAD

**Issue by cxcatir** [AnWeber/vscode-httpyac#165]
Hi, is it possible that httpYac can also support the GraphQL request syntax of Intellij Idea HTTP client and be compatible for development?

IntelliJ IDEA HTTP client:

use `GraphQL` keyword

```
GRAPHQL https://api.spacex.land/graphql

query launchesQuery($limit: Int!){
  launchesPast(limit: $limit) {
    mission_name
    launch_date_local
  }
}

{
    "limit": 10
}
```

Thanks a lot :bow:

**Comment by AnWeber** [comment]
I overlooked the difference. I will take a look, if I find a documentation and update my implementation.

**Comment by AnWeber** [comment]
With the next release GRAPHQL Method will be autmatically replaced with POST Method

**Comment by cxcatir** [comment]
I'm looking forward to the next release, thanks!

**Comment by AnWeber** [comment]
@cxcatir I haven't closed all differences to Intellij Http Client yet, but wanted to release the changes that are important to you. With v5.10.0 it is now available.
It still lacks support for streaming responses and multiple requests, but I'm already working on that.

**Comment by cxcatir** [comment]
Thanks for the quick release! :partying_face:
