### ISSUE TITLE
Possibility to copy variable values

### ISSUE THREAD

**Issue by woolfas** [AnWeber/vscode-httpyac#169]
New feature request.

During the http file lifecycle, there can be created a lot of variables, which are displayed in the VSCode Httpyac plugin. And that way Httpyac plugin actually provides a very convenient way (which I use a lot) to inspect most important data, which is created/received during complex http file execution.

What I miss is a possibility to copy variable name and value (or at least only value). If variable is an object, then its value should be copied as a JSON string.

Please consider implementing this feature.

**Comment by AnWeber** [comment]
Should already work on click ( https://github.com/AnWeber/vscode-httpyac/blob/main/src/provider/objectTreeItem.ts#L37). Will take a look at it.

**Comment by woolfas** [comment]
That actually works. Intuitively I expected a popup menu on the right click of a mouse and the ability to select "copy attribute name" and "copy value" commands.
But its really good to know about this feature. Thank you for explanation.

**Comment by AnWeber** [comment]
Vscode does not allow to open a context menu. Alternative is to implement a discrete Action icon at the end of the line to indicate copy feature. I test if both options work simultaneously.

**Comment by AnWeber** [comment]
I added icon inline to the value to indicate copy feature.
