### ISSUE TITLE
console.log output?

### ISSUE THREAD

**Issue by IntranetFactory** [AnWeber/vscode-httpyac#17]
I've added a script with console.log  But I see output neither in OUTPUT nor in DEBUG CONSOLE  So I'm wondering where I could find the script console output ?

![image](https://user-images.githubusercontent.com/7462342/109018137-da4adf80-7685-11eb-8cb8-a62e57602b7a.png)
![image](https://user-images.githubusercontent.com/7462342/109018377-10885f00-7686-11eb-8a21-93c05e61ddf5.png)

**Comment by AnWeber** [comment]
console.log is written to the Dev Tools. I currently also provide a log object that is written to the OutputChannel httpyac.
![console](https://user-images.githubusercontent.com/13434739/109048950-f6776c80-76d7-11eb-9c26-8124a19b7b7d.gif)
I would be reluctant to override console, as for scripts imported with require this would not work easily.
There is also the idea of creating a separate output channel. 
```
const vscode = require('vscode');
const channel = vscode.window.createOutputChannel('myChannel');
channel.AppendLine('It`s me Mario');
```

But you can also debug the script code. see #13

**Comment by IntranetFactory** [comment]
Would there be any option to redirect console.log to the "DEBUG CONSOLE" of VS Code eg with an Extension?    
   
I've seen #13 - which is so great. Not being able to add a debugger; statement was PIA in PostMan. Do you have any plans to add the possibility to directly set breakpoints?  From my understanding vscode.DebugAdapterTracker might make that possible. I've never used that, but https://github.com/microsoft/vscode-nodebook#implementation-notes indicates that this could make debugging outstanding.

**Comment by AnWeber** [comment]
I'll give it a try for inline scripts to provide a modified console. I've also read about redirecting this generically, but I get a slight chill at the thought, since I'm probably redirecting it for all extensions in the extension host.
Possibly the extension can provide even more debug functionality, but it is a time issue. And this use case is not such a high priority for me, because you could also develop the scripts outside my idea with for example jest.
I am always open for improvements and pull requests.

**Comment by AnWeber** [comment]
I added console workaround for inline scripts in Anweber/httpyac@f18f29c2823c318086e3e4c70d5c5941101c9edb

**Comment by AnWeber** [comment]
new version with fix is released. may you please test. thanks:-)

**Comment by IntranetFactory** [comment]
Thank you. That works well.    Now it would be nice to be able to disable or reduce the default output - so that I can just see "my" output.

**Comment by AnWeber** [comment]
You have convinced me. That also bothered me just as much with Postman.

**Comment by AnWeber** [comment]
Closing the Issue. If you have any questions just contact me again.
