### ISSUE TITLE
http-client.env.json request_rejectUnauthorized not working in v5.10.3

### ISSUE THREAD

**Issue by koopssharp** [AnWeber/vscode-httpyac#173]
Hi,

Great tool! I love it! I like to report a little defect in version v5.10.3.

In the last version v5.10.3 there is a defect. The request_rejectUnauthorized in not picked up from the http-client.env.json environment configuration. 

For example: 
```
 {
    "Local": {
        "request_rejectUnauthorized": false,
    }
 }
```
The setting is not picked up, and certificate chain validation is executed when executing the http request.

I currently use the v5.10.2 version, that is still working nicely.

**Comment by AnWeber** [comment]
It seems to work for me. The variable is used. But one problem was that the file is not valid JSON. 

```json
 {
    "Local": {
        "request_rejectUnauthorized": false
    }
 }
```

```http
GET https://expired.badssl.com/
```

**Comment by AnWeber** [comment]
I released a new version. Please test again and if it is not fixed reopen this issue. Thanks

**Comment by koopssharp** [comment]
@AnWeber : I just tested the new version 6.0.0. And the setting works as expected! 

Thank you for the patch/fix!
