### ISSUE TITLE
unintuitive order of multiple http-client.env.json files

### ISSUE THREAD

**Issue by usb79** [AnWeber/vscode-httpyac#175]
hi,

i am a big fan of your project and using it frequently. at the moment I am using rider on one side and my colleagues use vscode on the other side, that is why i am particularly dependent on interoperability (such as jetbrains http-client.env.json files).

description:
currently i have two configuration files "http-client.env.json" (global config) and "http-client.private.env.json" (local config for passwords that I only want locally without pushing them to VCS) but it only works in rider where the values of the private file overwrite the values of the "normal" one. the vscode-plugin prefers the variables of my "http-client.env.json" whereas i would also expect "http-client.private.env.json" to be preferred (as in rider). when i deleted the "http-client.env.json" file, it worked and even when after recreating it it worked as well (but only until restart of vscode).

possible solution:
if you can reproduce the issue and agree on my suspicion to prefer private.env.json files over "normal" .env.json files, you could rank them higher in your variable evaulation mechanism.

thanks a lot for your time and effort you put in this project!

**Comment by AnWeber** [comment]
Thanks for the tip. I have not come across this deviation to Intellij before. Of course I want to adjust the behavior. With the next release the discrepancy is corrected.
