### ISSUE TITLE
Using No Proxy

### ISSUE THREAD

**Issue by subinamathew** [AnWeber/vscode-httpyac#176]
How do we set up no proxy directly in http yac?
I use proxy settings for vscode but in it too, we cannot set no proxy ... can I set no proxy directly for httpyac?
something like "thunder-client.excludeProxyHostList": "localhost"

**Comment by AnWeber** [comment]
Unfortunately, I am just discovering that this is very difficult to do. About an own hook in a `.httpyac.js` file it would work. But I better add an explicit excludeList or metaData.

> .httpyac.js
```js
module.exports = {
configureHooks: (api) => {
  api.hooks.onRequest.addHook('delete_proxy', function (_request,context) {
   delete context.config.proxy;
  });
}
}

```

**Comment by AnWeber** [comment]
With next release a setting proxyExcludeList is added to ignore proxy setting. Alternativly you could ignore proxy setting with metadata `# @no-proxy`.
