### ISSUE TITLE
support prompt variables

### ISSUE THREAD

**Issue by Gxmadix** [AnWeber/vscode-httpyac#178]
Hello, I wanted to move from rest-client to httpyac, but I didn't figure out how to use prompt variables, is it supported ?

```
### SignIn
# @name authSignin
# @prompt email
# @prompt password
POST {{Endpoint}}/signin

{
  "email": "{{ email }}",
  "password":"{{ password }}"
}
```

**Comment by AnWeber** [comment]
Should work, see https://httpyac.github.io/guide/variables.html?#input-password-and-quickpick. But i ist it rarely.

**Comment by Gxmadix** [comment]
Yes, that works greatly and better than expected, there is also a password and pick for multi choices.
Thanks @AnWeber
