### ISSUE TITLE
Assertions are highlighted differently when JSON is present

### ISSUE THREAD

**Issue by utybo** [AnWeber/vscode-httpyac#187]
Hi! First, thanks for making httpYac, it's an amazing project :) 

Given the following httpYac file:

```http
### Request 1
POST https://httpbin.org/anything

?? status == 200

### Request 2
POST https://httpbin.org/anything

{
    "some": "json"
}

?? status == 200


### Request 3
POST https://httpbin.org/anything

someContent

?? status == 200
```

The assertion is highlighted incorrectly in "Request 2".

![image](https://user-images.githubusercontent.com/5175705/233088841-e76354ac-e4c3-40d0-b9f8-e5017c2670d8.png)

Despite having a body, request 3 is highlighted fine, so it seems that it's the braces `{}` that mess up the syntax highlighting. (Note that this is a purely visual bug, this is parsed and executed correctly by httpYac)

**Comment by AnWeber** [comment]
For syntax highlighting you still need to create your own `http.tmLanguage.json`, which is independent of the actual parsing. In this one it was not considered that `??` also terminates the JSON section. This is added with the next release.

**Comment by AnWeber** [comment]
thx for reporting:-)

**Comment by utybo** [comment]
Thank you for the quick fix! 👍🏻
