### ISSUE TITLE
Script not executed when 302

### ISSUE THREAD

**Issue by sir-farfan** [AnWeber/vscode-httpyac#189]
Hello
I'm trying to get some variables from a redirect output (location header) , currently I copy-paste them, I'm trying to put them in the global object for use in the next request but, for whatever reason, when I get the 302 status, the script never gets executed.

```
###
# @title scripting a redirect
https://httpbin.org/redirect-to?url=http://localhost:3000/some/failed/callback

{{
  console.info("whoot");
  $global.foo = "var";
}}
```

The call has about 3 redirects, at least the first 2 seem to have the code I need, the last one will always be 302 until we implement the callback (not even in the backlog yet).

Is there an [event](https://httpyac.github.io/guide/scripting.html#events) or something I can use to execute on every redirect to extract the information I need?

**Comment by jrussellsmyth** [comment]
The issue you are having is the final redirect to your non-existent endpoint will actually get a connection error

**Comment by sir-farfan** [comment]
I had to add `# @no-redirect`

**Comment by sir-farfan** [comment]
I'll give that a try, maybe better than the 3 @no-redirect's I'm using.
