### ISSUE TITLE
responseViewPreserveFocus not working

### ISSUE THREAD

**Issue by jakoss** [AnWeber/vscode-httpyac#19]
I have setting: `"httpyac.responseViewPreserveFocus": false` but whenever i run request response view takes the focus

**Comment by AnWeber** [comment]
According to the [documentation](https://code.visualstudio.com/api/references/vscode-api#TextDocumentShowOptions), the flag works the other way around. 
```
An optional flag that when true will stop the editor from taking focus.
```
But I have an error in the documentation and to the actual value. This I have now corrected. In the future the default is really true

**Comment by jakoss** [comment]
Setting this to true fixed issue, documentation mislead me :)
