### ISSUE TITLE
When I use @ref to reference a non-existent request, no error is prompted.

### ISSUE THREAD

**Issue by Faputa** [AnWeber/vscode-httpyac#197]
In this case, the lack of an error prompt can actually be very confusing for me.

![image](https://github.com/AnWeber/vscode-httpyac/assets/14192199/e6040b71-746c-450f-a012-8cfb418ce71e)

**Comment by AnWeber** [comment]
@Faputa Yes, [the error is simply swallowed](https://github.com/AnWeber/httpyac/blob/main/src/plugins/core/metaData/refMetaDataHandler.ts#L33). An abort would make more sense. Will fix it
