### ISSUE TITLE
Using $global with multiple environments

### ISSUE THREAD

**Issue by xlemassacre** [AnWeber/vscode-httpyac#207]
Hi, I have question regarding the $global variable in scripts.

I try to use that variable to write something from the response header in a global variable:
```
{{
  $global.logintoken = response.headers['authorization'];
}}
```
This is working fine when only one environment is selected. When using multiple environment (which is a really nice feature), the global variable is set in none of the selcted environments.

Would it be possible to store it to either one or all selected environments?

**Comment by AnWeber** [comment]
Actually, the global variable is created already [per environment combination](https://github.com/AnWeber/httpyac/blob/main/src/utils/environmentUtils.ts#L3). [I create a key over all environments and save the values}(https://github.com/AnWeber/httpyac/blob/main/src/plugins/javascript/globalVariableProvider.ts#L39). So if you choose the same combination you should get the previous value again. The saving can be seen in the session tab, but unfortunately you can't see for which environments the key is valid.

<img width="286" alt="image" src="https://github.com/AnWeber/vscode-httpyac/assets/13434739/b6e31a72-910f-4b0a-9fe8-37c0491c21d9">

You could view the Key in my debug view

<img width="246" alt="image" src="https://github.com/AnWeber/vscode-httpyac/assets/13434739/438e3307-cdea-4cf9-873f-60f9322b6ff4">

I could not reproduce the error with me now. Could you please describe in more detail why the values are not reused, preferably with an example

**Comment by xlemassacre** [comment]
Thanks for the quick response, took me some times now to do a retest. Seems to be working now actually, but unfortunatelly I don't know whats different this time. 
If it happens again I'll try to add more details :)
