### ISSUE TITLE
How to extract an <entry> inside <feed> XML response

### ISSUE THREAD

**Issue by miyamotoh** [AnWeber/vscode-httpyac#208]
Hi, I admit I'm not very familiar with XPath, but googling around, I came to suspect the below `.http` code might work and get me the first host ID of many that're returned from the `hosts` call prior at `<feed><entry><id>` in the response XML.
```
###
# @name spps
# @ref hosts
@xpath_ns atom=http://www.w3.org/2005/Atom
@host = {{$xpath.hosts //atom:entry[1]/atom:id}}
GET https://{{hmcsvr}}/rest/api/uom/ManagedSystem/{{host}}/SharedProcessorPool
Accept: application/atom+xml
X-API-Session: {{token}}
```
However, this `{{host}}` in the GET request remains empty, despite many variants that I've tried (again, I'm no expert). I hope I'm missing something obvious that an expert can point me to. Thanks!!

**Comment by AnWeber** [comment]
Your XPath is valid, but you should use a colon instead of `$xpath.host`

```
{{$xpath:hosts //atom:entry[1]/atom:id}}
```
You should see an error in the Output Channel
![image](https://github.com/AnWeber/vscode-httpyac/assets/13434739/f4d50167-eff6-45b4-8fb7-1c00d3df4de7)


Working example
```
###
# @name hosts
GET https://rss.golem.de/rss.php?ms=open-source&feed=ATOM1.0
Accept: application/atom+xml
###
# @ref hosts
# @name xpath_test
@xpath_ns atom=http://www.w3.org/2005/Atom
@host = {{$xpath:hosts //atom:entry[1]/atom:id}}
{{
  console.info(host)
}}
```

**Comment by miyamotoh** [comment]
Oh, never mind. I found `@extension` in the doc 🎉 , and that's all I needed for the weird `Content-Type` problem!
```
###
# @name emondata
# @ref login
# @ref energymon
# @extension json
@xpath_ns atom=http://www.w3.org/2005/Atom
GET {{$xpath:energymon //atom:entry[5]/atom:link/@href}}
Accept: application/json
X-API-Session: {{token}}
```
With this, the response editor window can "format document" as JSON. All set!

**Comment by AnWeber** [comment]
> Ah, great to know that little {{ console.info(host) }} trick to debug

I fear to spoil a generation of frontend devs, if I say you could debug with `console.info` :-). But yeah, I will mention it in my docs.
