### ISSUE TITLE
Generate code doesn't work if there are query parameters

### ISSUE THREAD

**Issue by ckazimie** [AnWeber/vscode-httpyac#21]
When I choose Generate code for a request containing a query parameter it fails with this error:
HARError: validation failed
Version 2.3.0

It doesn't matter what is the target platform generate it for
Example

GET http://abc.com/a?b=c

ERROR: http://abc.com/a?b=c
{
"url": "http://abc.com/a?b=c",
"method": "GET",
"http2": true,
"headers": {
"User-Agent": "httpyac"
},
"cookieJar": {
"version": "tough-cookie@4.0.0",
"storeType": "c",
"rejectPublicSuffixes": true,
"cookies": []
},
"followRedirect": true
}
ERROR: HARError - validation failed
HARError: validation failed

**Comment by AnWeber** [comment]
The name of the query string parameter in the HAR request is name and not key. The error is fixed with the new version.

**Comment by ckazimie** [comment]
Version 2.4.0 works very well now. Thank you.
