### ISSUE TITLE
[BUG] send 127.0.0.1:50001 http request failed with httpyac vscode plugin, 50001 is special port for this problem

### ISSUE THREAD

**Issue by li1234yun** [AnWeber/vscode-httpyac#214]
When I send http request with httpyac, if I use 50001 port to send request will throw error.

<img width="1551" alt="image" src="https://github.com/AnWeber/vscode-httpyac/assets/26505658/3e058745-64c5-4c00-b9e6-01f29efe0762">

`httpYac - Rest Client v6.6.3`

**Comment by AnWeber** [comment]
It seems that the error comes [directly from NodeJS](https://github.com/nodejs/llhttp/blob/926c982942eb53a13f01c1e9e6b19bd3b196e7dd/src/llhttp/http.ts#L317) and it occurs when parsing the HTTP response. I think at port 50001 there is no HTTP server or it responds with HTTP/2 or newer. I would expect HTTP/1.1 for this request. Can you call this once with curl and give me the response. Alternatively record it with Wireshark. The same issue was reported at Postman (https://github.com/postmanlabs/postman-app-support/issues/9176). There are some good tips for research in there.

**Comment by li1234yun** [comment]
Hi, @AnWeber 
This is my wrong usage. I send http request to GRPC server port.

<img width="1539" alt="image" src="https://github.com/AnWeber/vscode-httpyac/assets/26505658/355df206-93c5-44e4-ba4f-0fc804b444a2">

Thank you for your patient reply!

**Comment by AnWeber** [comment]
You're welcome. Interestingly, the GRPC also returns HTTP/0.9 during a curl call. Possibly just one falltrough issue of curl ([seems to be](https://github.com/curl/curl/blob/864090ca39c3c9fe994104ed23d29c37caa61a8e/lib/http.c#L4003)).
