### ISSUE TITLE
Feat: Keep response tab last position

### ISSUE THREAD

**Issue by andremacola** [AnWeber/vscode-httpyac#216]
It would be interesting to persist the position of the answer tab in the last location

When we use the client as in the image example, the position of the tab is always reset when a request is made

PS: I know about workbench.editor.openSideBySideDirection but it's not ideal as it changes the whole behavior of the editor

![210875566-9f8e93dd-f10d-45f9-9d70-5b296f6a3ce0](https://github.com/AnWeber/vscode-httpyac/assets/3408809/c68d864a-0aea-4a37-b9a9-4dc37c739d5f)

**Comment by AnWeber** [comment]
@andremacola You got the wrong extension. Your screenshots use [vscode.rest-client}(https://github.com/Huachao/vscode-restclient).  But I wish you good luck [that the bug will be fixed there](https://github.com/Huachao/vscode-restclient/graphs/code-frequency).
I think my extension already does it correctly. 
![view](https://github.com/AnWeber/vscode-httpyac/assets/13434739/48ddce4d-497f-4998-a412-3d5bdd48fafe)

**Comment by andremacola** [comment]
@AnWeber Thks for response. Yep, the screenshot is from rest-client but the behavior is equal on httpyack.

Try to put the http tab at the same side of the json results tab. Like this:


https://github.com/AnWeber/vscode-httpyac/assets/3408809/14743c8a-10e8-47ce-8fa7-60dbe2b3b36e

**Comment by AnWeber** [comment]
Now it should work better. Now the editor always opens in the same place as the previous preview, as desired. However, it is unfortunately possible due to the lack of interface that I restore the arrangement after closing the document.
![works](https://github.com/AnWeber/vscode-httpyac/assets/13434739/7f34d4d5-6a4e-4599-ab75-2bb492e2e1ec)

**Comment by andremacola** [comment]
That's nice. Works flawlessly
