### ISSUE TITLE
Outline can't find symbols, if asserts are present

### ISSUE THREAD

**Issue by bohni** [AnWeber/vscode-httpyac#219]
Outline OK:

![image](https://github.com/AnWeber/vscode-httpyac/assets/1252254/142df4fa-ed09-4ccd-8f7e-4e7c415e72f5)

```
### Latest launches
GET /launches/latest
```

Outline broken:

![image](https://github.com/AnWeber/vscode-httpyac/assets/1252254/0543e9a9-ffe8-41c4-8ff0-8933193e7873)

```
### Latest launches
GET /launches/latest

?? status == 200
```

Environment:
VS Code 1.82.0
httpYac v6.6.4

**Comment by AnWeber** [comment]
already fixed with https://github.com/AnWeber/httpyac/pull/542. but I need to release it
