### ISSUE TITLE
Syntax highlighting issue with Intellij scripts when JSON body is used

### ISSUE THREAD

**Issue by bratekarate** [AnWeber/vscode-httpyac#220]
When using the VSCode extension, the following example HTTP file in Intellij format is not highlighted correctly in the editor:

```
### postStuff
POST {{my_url}} HTTP/1.1
Content-Type: application/json

{
    "my": "data"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
```
Specifically the Intellij script is not colored correctly.

On the other hand, this works:

```
### postStuff
POST {{my_url}}
Content-Type: application/x-www-form-urlencoded

my=data

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
```

**Comment by AnWeber** [comment]
Syntax highlighting works with next release
<img width="473" alt="image" src="https://github.com/AnWeber/vscode-httpyac/assets/13434739/043f80a9-6dc5-4029-a88e-11c88d5a50e0">
