### ISSUE TITLE
http header and content-type completion is broken since v6.1.0

### ISSUE THREAD

**Issue by bigsan** [AnWeber/vscode-httpyac#223]
Because of the completion items in `src/provider/httpCompletionItemProvider.ts` were removed, instead it tries to load from `plugins/http/completionItemProvider.ts` in `httpyac` modules which was not imported anywhere in that module.

The `index.ts` under `http`, `eventsource` and `websocket` plugins in `httypyac` module didn't contain `import "./completionItemProvider"`, which causes this problem.

I don't know if that was intentional or a bug,  hope this can be fixed soon 😀.

**Comment by AnWeber** [comment]
@bigsan I haven't fully understood what's broken. You have a commit for me because you seem to have already identified the code.

**Comment by AnWeber** [comment]
fixed. with v6.6.7
