### ISSUE TITLE
Markdown response not updated when request repeated with a different body

### ISSUE THREAD

**Issue by manderson23** [AnWeber/vscode-httpyac#226]
When I have multiple requests like the following
```
POST https://host/api/invoke
{
  "commandName": "command1"
}

POST https://host/api/invoke
{
  "commandName": "command2"
}
```
I execute them in order and the response bodies are shown correctly in the preview.

However, when I open the markdown for the second POST it still shows the details of the first POST.

**Comment by AnWeber** [comment]
@manderson23 It seems to be a bug in the markdown preview editor. I try to create a unique meaningful filename for storing the response based on the name or url. Unfortunately this does not work here and both requests have the same file name. When displaying I just add the extension `.md` and display this file. Here however then the previous request is represented. If I open the file on the hard disk or in VSCode Editor, the correct content is displayed. It seems that the Markdown Preview uses some kind of caching.

![markdown_bug](https://github.com/AnWeber/vscode-httpyac/assets/13434739/884924c0-3bf9-41e2-9715-e145b5fbc5f2)

**Comment by AnWeber** [comment]
here the same bug without my extension 
![markdown_bug](https://github.com/AnWeber/vscode-httpyac/assets/13434739/8c174247-86de-4239-b8e4-ecd566cb8322)

**Comment by AnWeber** [comment]
@manderson23 I added some kind of cache busting to prevent the VSCode Bug. I will remove this hack after fix of  vscode issue.
