### ISSUE TITLE
VSCode: The requested URL could not be retrieved

### ISSUE THREAD

**Issue by QuAzI** [AnWeber/vscode-httpyac#227]
I have http script which works fine in JB apps and in console
```
httpYac send .\migration-script.http -e development -n Login --insecure
```
But from VSCode it always return 500 with comment `The requested URL could not be retrieved`

`migration-script.http`
```rest
### Login
POST https://{{host}}/app/identity/api/login
Content-Type: application/json

{"email":"{{username}}","password":"{{password}}","rememberme":true,"nextPage":""}

> {%
    client.test("Authorization tests", function() {
      client.assert(response.status === 200, "Response status is not 200");
      client.assert(response.body.hasOwnProperty("success"), "Cannot find 'success' option in response");
      client.assert(response.body["success"] == true, `Status is ${response.body["success"]}`);
    });
    client.global.set("userId", response.body["userID"]);
%}
```

`http-client.private.env.json`
```json
{
    "development": {
        "host": "local.somesite",
        "username": "login@mail",
        "password": "pass"
    }
}
```

**Comment by AnWeber** [comment]
@QuAzI  I cannot understand the error. I am trying to recreate the setup.

- create file `http-client.private.env.json` and `migration-script.http` in the same folder and copy content
- open file with vscode
- select environment `development`
- I should see some bug 

Observed: It uses correct environment

![setup](https://github.com/AnWeber/vscode-httpyac/assets/13434739/bf7c9df4-1ae3-4df4-bd9f-7ed1871d9e33)

**Comment by QuAzI** [comment]
It looks like connected to the local self-signed certificate for microservice in Docker. Because the same request for public version works fine. In CLI version I used `--insecure` parameter and it's works but it's not so comfortable in development. But I don't know how to use the same option in VSCode or how to pass self-signed certificate from local Cert Manager to VSCode plugins. JB tool and my own .NET project works fine with this certificate.

**Comment by AnWeber** [comment]
look at docs: https://httpyac.github.io/guide/troubleshooting.html#turn-off-verification-of-self-signed-certificate

It is a NodeJS issue which provides its own cert store. Maybe using [win-ca extension](https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca) also solves your problem.

**Comment by QuAzI** [comment]
Thanks a lot, I found the reason. It was my fault - I forgot about proxy settings in VSCode
