### ISSUE TITLE
TestResults always empty

### ISSUE THREAD

**Issue by QuAzI** [AnWeber/vscode-httpyac#228]
I am not sure what should be there but after request execution I can see link "TestResults" which opens empty Markdown file

https://github.com/AnWeber/vscode-httpyac/assets/1897605/d857ccd3-b1cd-4496-af6a-d854678325ad

**Comment by AnWeber** [comment]
@QuAzI I had an error in the logic of how I find the Responses for the HttpRegion. As a result, the CodeLens was broken. Now it should work again. I don't notice that, because I have deactivated in my setup :-(
