### ISSUE TITLE
[BUG] Broken environment loading

### ISSUE THREAD

**Issue by vojtech-pejsa-redbit** [AnWeber/vscode-httpyac#230]
Version 6.7.0 broke environment loading when launching requests as tests, send action doesn't seem to be affected.

## Steps to reproduce

1) Open file test.rest.
2) Click on action ``env:`` and select environment demo. 
3) Click green triangle to run test.
4) Result is error: ``page is not defined``

Action ``send`` works correctly with the same workflow.

Version 6.6.7 works without any problems.

## Test files:

test.rest:
```
GET https://reqres.in/api/users?page={{page}}
```

httpyac.config.js:
```
module.exports = {
  environments: {
    demo: {
        page: 2
    }
  },
};
```

**Comment by AnWeber** [comment]
Unfortunately, I overlooked that this is the setting of `testRunAlwaysUseEnv` always truthy. I will correct it today.

**Comment by vojtech-pejsa-redbit** [comment]
Thank you for quick fix :slightly_smiling_face:.
