### ISSUE TITLE
httpRegion.httpFile.activeEnvironment  does not exist

### ISSUE THREAD

**Issue by z0y1** [AnWeber/vscode-httpyac#233]
with the latest version of httpyac, `console.info(httpRegion.httpFile.activeEnvironment);` always return null. even if env is setup.

**Comment by AnWeber** [comment]
Hi yes sorry. this no longer exists. Since this recently would not contain the correct value in all cases and I wanted to avoid using it by mistake. Please use `console.info($context.activeEnvironment)` instead.
