### ISSUE TITLE
Syntax highlight missing for next line of a commentted query item line

### ISSUE THREAD

**Issue by 7sDream** [AnWeber/vscode-httpyac#234]
![image](https://github.com/AnWeber/vscode-httpyac/assets/7822577/247e48e7-44f2-4deb-ac7a-8de52a5d1f91)

I found this when I try to figure out how to disable a query item temporarily.

Comment works like expect, but seems this is not introduced in [querystring doc page](https://httpyac.github.io/guide/request.html#query-strings).

And, BTW, if there an easy way to make a query item only sent in a specific env?

**Comment by AnWeber** [comment]
I have added the highlighting. Thanks for the hint.
