### ISSUE TITLE
How about adding some shortcut keys like jupyter notebook ?

### ISSUE THREAD

**Issue by yangchnet** [AnWeber/vscode-httpyac#237]
🥰I am very happy to have found such an easy-to-use REST client that can meet all my needs. I like the way to manage interfaces like documents. 

When I use the httpBook extension, it is very similar to the UI of jupyter notebook, so I habitually press `b` to create a new cell, but it does not work as expected.

So can we add some shortcut keys like this?

Here are some introductions to jupyter notebook shortcut keys：https://towardsdatascience.com/jypyter-notebook-shortcuts-bf0101a98330

**Comment by AnWeber** [comment]
There are actually already the comands by default in VSCode (`notebook.cell.insertCodeCellBelow`). Only the default shortcuts use different keybindings. You just have to adapt them to your needs ([see](https://code.visualstudio.com/docs/getstarted/keybindings)).

<img width="998" alt="image" src="https://github.com/AnWeber/vscode-httpyac/assets/13434739/ac77c8ed-15cb-4280-893c-339df8025136">
