### ISSUE TITLE
[feature] import curl

### ISSUE THREAD

**Issue by maicss** [AnWeber/vscode-httpyac#238]
Excellent work, thanks!

Would you like to add a function:  `import curl command`?

**Comment by myfonj** [comment]
I'd also highly appreciate the other way round **(export)**: `copy request as curl command`
I.e. all effective request data (including those from resolved `ref`s) and serialized them all one compact chunk of `curl -X .. -H .. -H .. -d ....` that one could immediately try in terminal or share with folks that have not httpYac available.

**Comment by AnWeber** [comment]
@myfonj Export Feature is already supported. You can use command `httpyac.generateCodeSelectLanguage` (default output curl ito clipboard) or `httpyac.generateCode` to select generated language.

I don't quite see the use case for import. curl can actually already be run anyway and the added value with import is low. I actually want/need to write an OpenAPI import sometime soon, so this feature may fall out as a byproduct, [But I had already discussed it away once](https://github.com/AnWeber/httpyac/issues/301). Gladly but PR integrable. I can also help. Alternatively, I would refer to this page.: https://reqbin.com/req/c-w7oitglz/convert-curl-to-http-request
