### ISSUE TITLE
OAuth2 / OpenID Connect - Error

### ISSUE THREAD

**Issue by bohni** [AnWeber/vscode-httpyac#240]
I have an oAuth2 server whose responses do not contain the attribute `expires_in`.

When using [OAuth2 / OpenID Connect](https://httpyac.github.io/guide/variables.html#oauth2-openid-connect), the requests and responses of the necessary token request are shown in a VS Code window, but the request under test does not get executed.

In [Access Token Response](https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/) the attribute `expires_in` is marked as `recommended`, not as `required`.

Does the feature "OAuth2 / OpenID Connect" rely on that attribute?

Those tokens themself have their expiration time included. To get that value, jwd decode could be used.

Edit:

I did a simple test with a hard coded response of that server and a simple Spring Boot App. If the `expires_in` attribute is present, the request under test runs as expected.

**Comment by AnWeber** [comment]
Do you use deviceCodeFlow? There may be an issue, when property is not set (https://github.com/AnWeber/httpyac/blob/8feaa0aff2f47de3dda831495868f1983c2e2689/src/plugins/oauth2/flow/deviceCodeFlow.ts#L44).

**Comment by AnWeber** [comment]
fixed with v6.10.0

**Comment by bohni** [comment]
Wow, that was fast. And it works. Thank you!
