### ISSUE TITLE
env from http-client.private.env.json overwritten with values from template-http-client.private.env.json

### ISSUE THREAD

**Issue by bohni** [AnWeber/vscode-httpyac#245]
Hi,

we are using a Maven archetype to generate similar projects.

The archetype creates the file `temlate-http-client.private.env.json` that contains the keys of the secrets with fake values and is committed to the VCS

    {
        "DEV": {
            "secret": "todo"
        }
    }

The developer copies the file to `http-client.private.env.json` and enters the real secrets. This file is ignored by VCS.

When running a request the value from `http-client.private.env.json` is ignored and the one from the template is used.

![image](https://github.com/AnWeber/vscode-httpyac/assets/1252254/18210545-2343-418f-a285-767d32e99979)

**Comment by AnWeber** [comment]
I wasn't quite sure exactly what Intellij's logic was here. For this reason, I have accepted all env.json files. But according to the documentation only http-client.env.json and http-client.private.env.json seem to be allowed. I restrict it.
