### ISSUE TITLE
JSON key that has spaces un-referencable when using variable injection

### ISSUE THREAD

**Issue by Spitfire1900** [AnWeber/vscode-httpyac#246]
I have the following script, I have attempted to use both `{{login.JWT Authentication.rawHeaderValue}}` and `{{login.'JWT Authentication'.rawHeaderValue}}` to re-use the `JWT Authentication` key's `rawHeaderValue` property from the `login` response body; however I get the following errors:

```
ERROR: SyntaxError - Unexpected identifier 'Authentication'
c:\Users\XXXXX\Repos\jwt-issue.http:12
exports.$result = (login.JWT Authentication.rawHeaderValue);
```

```
ERROR: SyntaxError - Unexpected string
c:\Users\XXXXX\Repos\jwt-issue.http:12
exports.$result = (login.'JWT Authentication'.rawHeaderValue);
```

Script
```
@baseUrl = https://mycompany.com/echoRequest
# @name login
GET {{baseUrl}}
Authorization: Basic {{$dotenv USERNAME}}:{{$dotenv PASSWORD}}


###
# @ref login
GET {{baseUrl}}
Authorization: Bearer {{login.'JWT Authentication'.rawHeaderValue}}
```

**Comment by Spitfire1900** [comment]
This is resolved using bracket notation, while part of the JavaScript spec docs on this at https://httpyac.github.io/guide/metaData.html#name would be useful.

```
 GET {{baseUrl}}
Authorization: Bearer {{login["JWT Authentication"].rawToken}}
```

**Comment by AnWeber** [comment]
Can you give me suggestions how to improve the docs ( see https://httpyac.github.io/guide/variables.html#nodejs-script). I already mentioned usage of NodeJS.

**Comment by Spitfire1900** [comment]
This may be closed as a skill issue.
