### ISSUE TITLE
Input unexpected behavior

### ISSUE THREAD

**Issue by Gxmadix** [AnWeber/vscode-httpyac#247]
Hello, I am facing an unexpected behavior with an optional input field, like explained below.

```
### SignIn
@email = {{ $input email value? }}
@password = {{ $password password! }}
@account = {{ $input optional select the wanted profile }}
POST {{AuthUrl}}/signin HTTP/{{httpVersion}}

{
  "email": "{{email}}",
  "password": "{{password}}",
  "account": "{{account}}"
}
```

When I leave @account empty, I receive this 
```
## Received
{
  email: 'email@stuff.com',
  password: 'ThePassword',
  account: '{{account}}'
}
```

But logically this shouln'd be filled, I am expecting something more like this.
```
####
## Expected
{
  email: 'email@stuff.com',
  password: 'ThePassword'
}

or 

{
  email: 'email@stuff.com',
  password: 'ThePassword',
  account: ''
}
```

**Comment by AnWeber** [comment]
default error of mine. `undefined !== "" ` in line https://github.com/AnWeber/httpyac/blob/main/src/plugins/core/replacer/showInputBoxVariableReplacer.ts#L44C5-L44C5 I will fix it.

**Comment by AnWeber** [comment]
fixed with next release
