### ISSUE TITLE
Nodejs parsing for query params

### ISSUE THREAD

**Issue by natalie-o-perret** [AnWeber/vscode-httpyac#249]
🙋‍♀️ Hello, it's again wee me!

# Context

I have to deal some API (not mine), and the query params can pretty verbose I found only two ways to handle this case but none of them make things conveninent from my point of view:

# Workarounds

## Workaround 1: Full verbose variables

```bash
### Get Whatever data
# @name getWhateverData
# @forceRef getExchangeToken
@id1=21720000
@id2=21100000
@id3=21100100
@id4=21300000
@id5=21200000
@id6=21302000
@id7=21310000
@id8=24020500
@id9=24020598
@id10=24020599
@id11=24020000
@id12=24020300
@id13=12590000
@id14=12110000
GET {{apiHost}}/api/v1/entities
    ?id={{id1}}
    &id={{id2}}
    &id={{id3}}
    &id={{id4}}
    &id={{id5}}
    &id={{id6}}
    &id={{id7}}
    &id={{id8}}
    &id={{id9}}
    &id={{id10}}
    &id={{id11}}
    &id={{id12}}
    &id={{id13}}
    &id={{id14}}
Authorization: Bearer {{getExchangeToken.access_token}}
```
But as you can see, it's super verbose and time-consuming to type all the ids😕

## Workaround 2: Nodejs script

```bash
### Get Whatever data
# @name getWhateverData
# @forceRef getExchangeToken
GET {{apiHost}}/api/v1/entities?{{[21720000, 21100000, 21100100, 21300000, 21200000, 21302000, 21310000, 24020500, 24020598].map(x => `entityId=${x}`).join('&')}}
Authorization: Bearer {{getExchangeToken.access_token}}
```

So this works, but I see 2 main caveats:
- I would rather like to have the array as a variable and then use it in the nodejs segment
- The syntax doesn't support having the query params on another different line (which can make combining with another type of parameter again on the same line), i.e., 
  - While this works:
   ```bash
   GET {{apiHost}}/api/v1/entities?{{[21720000, 21100000, 21100100, 21300000, 21200000, 21302000, 21310000, 24020500, 24020598].map(x => `id=${x}`).join('&')}}
   ```
   - This doesn't:
   ```bash
   GET {{apiHost}}/api/v1/entities
       ?{{[21720000, 21100000, 21100100, 21300000, 21200000, 21302000, 21310000, 24020500, 24020598].map(x => `id=${x}`).join('&')}}
   ```

# Proposal

```bash
### Get Whatever data
# @name getWhateverData
# @forceRef getExchangeToken
@ids=[21720000, 21100000, 21100100, 21300000, 21200000, 21302000, 21310000, 24020500, 24020598]
GET {{apiHost}}/api/v1/entities
    ?{{{{ids}}.map(x => `id=${x}`).join('&')}}
Authorization: Bearer {{getExchangeToken.access_token}}
```
But it doesn't seem to work 🤔

If something similar is already available, please feel free to point me towards that solution.

Also would love some support for multiple lines variable definitions, e.g., 

```bash
@ids=[
  21720000, 
  21100000, 
  21100100, 
  21300000, 
  21200000, 
  21302000, 
  21310000, 
  24020500, 
  24020598
]
```

Wdyt?

**Comment by AnWeber** [comment]
using NodeJS Script should work.

```
{{ 
  exports.ids=[
  21720000, 
  21100000, 
  21100100, 
  21300000, 
  21200000, 
  21302000, 
  21310000, 
  24020500, 
  24020598
]
}}
GET {{apiHost}}/api/v1/entities
    ?{{ids.map(x => `id=${x}`).join('&')}}
```

**Comment by natalie-o-perret** [comment]
Hey there @AnWeber, thanks for being responsive, you're amazing!

So about what you just suggested:
> using NodeJS Script should work.
> 
> ```
> {{ 
>   exports.ids=[
>   21720000, 
>   21100000, 
>   21100100, 
>   21300000, 
>   21200000, 
>   21302000, 
>   21310000, 
>   24020500, 
>   24020598
> ]
> }}
> GET {{apiHost}}/api/v1/entities
>     ?{{ids.map(x => `id=${x}`).join('&')}}
> ```

It kinda works, but there is some hiccup:

It works if the `?` query param prefix is one the same line as the host stuff, i.e.,

```bash
GET {{apiHost}}/api/v1/entities?{{ids.map(x => `id=${x}`).join('&')}}
```
leading effectively to (when evaluated by httpyac):
```bash
GET https://my-api.com/api/v1/entities?id=21720000&id=21100000&id=21100100&id=21300000&id=21200000&id=21302000&id=21310000&id=24020500&id=24020598
```

That being said, when it's on new line:
```bash
GET {{apiHost}}/api/v1/entities
    ?{{ids.map(x => `id=${x}`).join('&')}}
```

It ends being interpreted: 

```
GET https://my-api.com/api/v1/entities
accept-encoding: gzip, deflate, br
accept: */*
content-length: 3458
user-agent: httpyac

    ?id=21720000&id=21100000&id=21100100&id=21300000&id=21200000&id=21302000&id=21310000&id=24020500&id=24020598
Authorization: Bearer my-amazingly-long-bearer-token
```

It's like the extra line messing things which oddly-enough isn't the case with the "Workaround 1: Full verbose variables" I mentioned in my original post, do you know what that might be the case?

**Comment by AnWeber** [comment]
Yes, I just noticed that too, the parser for the URL is probably not quite right. I'll have to have a look at the regex.
One more addition, I also have a helper method that makes it easier to create query params, but it can only create arrays with the next release. I haven't needed it yet and am currently adding it.

```
{{ 
const {utils} = require("httpyac");
  exports.q=utils.toQueryParams({ id: [
  21720000, 
  21100000, 
  21100100, 
  21300000, 
  21200000, 
  21302000, 
  21310000, 
  24020500, 
  24020598
]})
}}
GET http://postman-echo.com/get?{{q}}
```

**Comment by natalie-o-perret** [comment]
> Yes, I just noticed that too, the parser for the URL is probably not quite right. I'll have to have a look at the regex. One more addition, I also have a helper method that makes it easier to create query params, but it can only create arrays with the next release. I haven't needed it yet and am currently adding it.
> 
> ```
> {{ 
> const {utils} = require("httpyac");
>   exports.q=utils.toQueryParams({ id: [
>   21720000, 
>   21100000, 
>   21100100, 
>   21300000, 
>   21200000, 
>   21302000, 
>   21310000, 
>   24020500, 
>   24020598
> ]})
> }}
> GET http://postman-echo.com/get?{{q}}
> ```

Nice! Can't wait 🪩💃!

**Comment by AnWeber** [comment]
I released a update containing these fixes.
