### ISSUE TITLE
sent GraphQL request without content type header and got error

### ISSUE THREAD

**Issue by cxcatir** [AnWeber/vscode-httpyac#257]
Hi, I sent GraphQL request and got error `Cannot read properties of undefined (reading 'launchesQuery')`

```
GRAPHQL https://api.spacex.land/graphql

query launchesQuery($limit: Int!){
  launchesPast(limit: $limit) {
    mission_name
    launch_date_local
  }
}

{
    "limit": 10
}
```

Is it possible that httpYac can also support the GraphQL request without header `Content-Type`?

GraphQL syntax is without Content-Type header in built-in plugins HTTP Client of Jetbrain IDE.  It would be great to have support. Thank a lot :bowing_woman: 

https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html#graphql

**Comment by AnWeber** [comment]
Yes, agree that should work the same. Feel free to create a bug in case of deviations. I don't use Intellij at all at the moment and you don't document changes so precisely in updates.
fixed and released in v6.11.3
