### ISSUE TITLE
Doesn't assert number value 

### ISSUE THREAD

**Issue by rabestro** [AnWeber/vscode-httpyac#260]
The request file:

```http
{{host}}/actuator/health

?? status == 200
?? body status == UP
?? body components.diskSpace.status == UP
?? body components.diskSpace.details.total > 0
?? body components.diskSpace.details.free > 0
```

### Error message

✖: components.diskSpace.details.total > 0 (AssertionError [ERR_ASSERTION]: components.diskSpace.details.total (36671356928) > 0 - /Users/jegors/.vscode/extensions/anweber.vscode-httpyac-6.11.4/dist/extension.js:191:46440)  
✖: components.diskSpace.details.free > 0 (AssertionError [ERR_ASSERTION]: components.diskSpace.details.free (17609199616) > 0 - /Users/jegors/.vscode/extensions/anweber.vscode-httpyac-6.11.4/dist/extension.js:191:46440)

**Comment by AnWeber** [comment]
A standard mistake that I unfortunately always make. 0 is falsy and I had a check to see if the value was present. Please simply change the check to > 1 until the bugfix is released

```
{{host}}/actuator/health

?? status == 200
?? body status == UP
?? body components.diskSpace.status == UP
?? body components.diskSpace.details.total > 1
?? body components.diskSpace.details.free > 1
```
