### ISSUE TITLE
Assertion doesn't work with zero nubers

### ISSUE THREAD

**Issue by rabestro** [AnWeber/vscode-httpyac#262]
```http
{{host}}/actuator/translationcount

?? status == 200
?? body count isNumber
?? body count >= 0
```

### TestResults

✓: status == 200
✖: count isNumber (AssertionError [ERR_ASSERTION]: count (false) isNumber - /Users/jegors/.vscode/extensions/anweber.vscode-httpyac-6.11.4/dist/extension.js:191:46440)
✖: count >= 0 (AssertionError [ERR_ASSERTION]: count (false) >= - /Users/jegors/.vscode/extensions/anweber.vscode-httpyac-6.11.4/dist/extension.js:191:46440)

**Comment by AnWeber** [comment]
seems to be a duplicate of #260
