### ISSUE TITLE
IntelliJ variables broken

### ISSUE THREAD

**Issue by kobmik** [AnWeber/vscode-httpyac#277]
The latest update (6.13.0) broke the IntelliJ variables.
In my case, $random.integer(70000000, 99999999) returns the value "78741155.22521658".
It looks like a float number will be generated instead of an integer.

**Comment by AnWeber** [comment]
Sorry, I accidentally deleted the implementation. I overlooked the difference to `$random.float` and combined the two methods. Oops. I have now added tests.
