### ISSUE TITLE
Test controller runs wrong tests

### ISSUE THREAD

**Issue by kobmik** [AnWeber/vscode-httpyac#278]
In some cases, the test controller starts a test other than the one selected (single test inside a http file).
Instead it runs a different test inside the file.
After selecting the button "Refresh Tests", the controller starts to run the correct test again.

**Comment by AnWeber** [comment]
The reason for this is that the tests do not update as quickly. Unfortunately, I cannot save a reference to my object directly to a TestItem. For this reason, I build this up using the current line of the TestItem to my object. However, when changes are made in the http, this does not always match directly. 
I was currently able to work around this by actively saving. Then a refresh is automatically executed internally and the items fit together again. I'll see what I can do.

![run_outdated_test](https://github.com/AnWeber/vscode-httpyac/assets/13434739/1048fa50-36ed-41ac-8668-d2473023b3d9)

**Comment by AnWeber** [comment]
I now also listen for onDidChangeTextDocument in order to react to changes without saving them
