### ISSUE TITLE
Global scripts not executed with @request

### ISSUE THREAD

**Issue by slackwareer** [AnWeber/vscode-httpyac#281]
The script below contains a global region and a test region(only JavaScript with no request named test-1) . When executing test-1 region , the first global region **cannot** be executed. An exception will be raised during exec of the test-1 region.
```js
{{@request
  exports.host = 'https://github.com';
  console.log('Global Script executed.');
}}

### test-1
GET {{host}} HTTP/1.1
```
![image](https://github.com/AnWeber/vscode-httpyac/assets/239952/c36f59bb-f099-4872-a1be-5ce31717f5ca)

But when the @request is removed, the test-1 regions will run successfully..
```js
{{
  exports.host = 'https://github.com';
  console.log('Global Script executed.');
}}

### test-1
GET {{host}} HTTP/1.1
```
![image](https://github.com/AnWeber/vscode-httpyac/assets/239952/a530550d-cc2d-42eb-98d4-7b318a9d2c91)

Maybe the variable replace hookitem should be moved after the @request region , just before the request execution?

**Comment by AnWeber** [comment]
@slackwareer The behavior is intentional. I only added the request hooks later. I wanted to offer an easy way to change/extend the replaced request again later. The difference between an execute and the request hook is basically the replacement.
