### ISSUE TITLE
Best Practice

### ISSUE THREAD

**Issue by davidsoles** [AnWeber/vscode-httpyac#282]
I love this vscode extension, thanks.
I was wondering, what is the best practice in terms of number of rest endpoints that can be added to a single `http` file? Is it better to have one `http` file per feature? 🤔 

I'm just trying to keep things organized.

**Comment by AnWeber** [comment]
I can't give you a general recommendation. Depending on the service, a different structure may make sense. I have sometimes structured the files like CRUD (PUT => GET => PATCH, => DELETE) and executed them one after the other. In some cases, however, a create a test http file containing only one endpoint with several tests. I'm a fan of small files, so I avoid packing lots of requests into one file.

My current setup can be described as follows:
- Separation between http files for testing and those for research/ debugging. I always forget to reset my changes when debugging.
- Using [`HTTPYAC_ENV`](https://httpyac.github.io/guide/environments.html#dotenv) I globally inject the necessary variables for the different environments (dev,prod). I can quickly open a window at any time and send a request against a system in which I select the respective environment.
- I inject the necessary authentication/header using a [private plugin (HTTPYAC_PLUGIN)](https://httpyac.github.io/plugins/#naming-and-discoverability). Again, the goal is that I can simply execute queries quickly (debugging) 
- Using snippets to generate often used payloads (e.g. OpenSearch Term query)
- I also have a central git repository, for requests that I don't need often but don't want to forget, e.g Keycloak Administration, List all repositories of Gitlab Server,...
