### ISSUE TITLE
help with http-client.env.json from intellij

### ISSUE THREAD

**Issue by martinm1000** [AnWeber/vscode-httpyac#289]
Hi,

I'm trying to use working intellij .http files in vscode (which I'm not very familliar with).
I've seen from your documentation that `http-client.env.json` placed beside a .http file should be recognized, 
but when I try to select an environment, the popup (select environment) doesn't list anything ?

requests works great if I hardcode my variables, so... am I doing something wrong ?

**Comment by AnWeber** [comment]
Hi Take a Look in my examples https://github.com/httpyac/httpyac.github.io/tree/main/examples/project/intellijEnvironments. These should work.

**Comment by martinm1000** [comment]
Hi ! 

Your example works ! 

Mine doesn't and I'm still looking at finding out why. Anything special in your processing of the contents of the files ?

Do your plugin have a log file somewhere that could help ?

**Comment by martinm1000** [comment]
Ok, I think I found out the source of the problem ! It appears I have unicode BOM bytes in my json files, which also existed in the files in Rider. When modifying your own example files, I also got the problem and I see : 
![image](https://github.com/AnWeber/vscode-httpyac/assets/3790866/fdeced09-53a0-4625-b9d7-a05a3f465877)

So I guess the problem is on my env. Had this problem with xml files in the past, its a first with JSON !

**Comment by martinm1000** [comment]
I can confirm this is my problem, than you. I'll need to sort out why I get these, As it looks like this is illegal for json files it seems.

![image](https://github.com/AnWeber/vscode-httpyac/assets/3790866/1a28c022-ff2b-477b-8a49-84c4f64bdbe8)

https://en.wikipedia.org/wiki/Byte_order_mark#Byte-order_marks_by_encoding

Thank you !

**Comment by AnWeber** [comment]
According to RFC default is UTF-8. https://www.rfc-editor.org/rfc/rfc4627#section-3
I read the bytestream in this encoding, without any fallback or encoding detection.

**Comment by martinm1000** [comment]
Yeah, the (updated) spec mentions that BOM bytes should not be used, so even if intellij seems to not have a problem with them, I guess you do not have anything else to fix on your side (unless you want to ignore those bytes). https://www.rfc-editor.org/rfc/rfc7159#section-8.1
