### ISSUE TITLE
requestGotOptions not working as expected

### ISSUE THREAD

**Issue by ethanmillard** [AnWeber/vscode-httpyac#29]
I'm unable to make requests against my local dev environment without a proper certificate. 
I always get `RequestError - unable to verify the first certificate`. 
This doesn't happen with the CLI, only through the extension.

I tried updating the `requestGotOptions` to set `rejectUnauthorized` to `false`. But that doesn't seem to work.
The type of `requestGotOptions` is also set as `objct` instead of `object`. But I'm not sure if that is the issue or not.

**Comment by AnWeber** [comment]
Thanks for the hint with the issue in configOptions.
Vscode and cli uses the identical code. One difference is the setting for http proxy. In vscode the setting http.proxy is observed. In addition, in vscode Insider I also have problems related to the proxy. Does this help you?

**Comment by AnWeber** [comment]
You also could set rejectUnauthorized in a script block as workaround.

```
{{
request.rejectUnauthorized=false;
}}
```

It should work, but I cannot test it at the moment.

**Comment by ethanmillard** [comment]
Neither of those seemed to work for me.
I did have my vs code settings `"http.proxyStrictSSL": false,`
And I also tried to script, but both gave me no change.

I'll just use an actual certificate though so it's not a big deal.

**Comment by AnWeber** [comment]
I'm afraid I gave you the wrong setting. [Got](
https://www.npmjs.com/package/got#advanced-https-api) expected the setting `rejectUnauthorized` under https. the following would have been correct.
```js
{{
Object.assign(request, { 
  https: {
    rejectUnauthorized: false
  }
});
}}
```

**Comment by ethanmillard** [comment]
Thank you @AnWeber. When I added the pre-script that worked.
Thanks for taking the time.

Do you think that would also work with the `requestGotOptions` in settings?

**Comment by AnWeber** [comment]
It should actually work. I'm just not sure because of the type error on the settings. If it does not work just add a plus sign to the script, so it gets a script, which is executed on every request. After the next release it should be fixed.

```js
{{+
Object.assign(request, { 
  https: {
    rejectUnauthorized: false
  }
});
}}
```
