### ISSUE TITLE
Syntax highlighting in request output breaks after a truncated request

### ISSUE THREAD

**Issue by alekdavisintel** [AnWeber/vscode-httpyac#295]
If the response from an HTTP request is longer than the configured max, it will be trunctcated in the `httpac - Request` window with the `... (xxx characters more)` message. This messes syntax highlighting of the rest of the request output:

![image](https://github.com/AnWeber/vscode-httpyac/assets/98194335/822e664d-30f3-4c4c-a771-c8671432b8d4)

I suspect this is caused because the returned JSON is not properly closed which may be tricky to handle, so I suspect there may be no easy fix, but wanted to mention it just in case. Maybe there is an option to not do syntax highlighting for truncated entries? Or maybe there are other workarounds? For now, I just increased the max length to 4K, which still may not work in some cases. Not sure if there is a better way.

**Comment by AnWeber** [comment]
fixed with next release

<img width="371" alt="image" src="https://github.com/AnWeber/vscode-httpyac/assets/13434739/b1920920-4eb8-4ad3-aad8-eb7046326ac1">

**Comment by alekdavisintel** [comment]
You rock!!!
