### ISSUE TITLE
VSCode does not like some httpyac.codelens configuration options in the settings.json file

### ISSUE THREAD

**Issue by alekdavis** [AnWeber/vscode-httpyac#314]
It looks like VSCode does not recognize the following properties in the settings.json file (I am using a local project file):

- generateCode
- showVariables
- validateVariables

![image](https://github.com/user-attachments/assets/b286ad03-13cf-47a8-bc45-c01f42c74b98)

I validated that the properties work, so must be just a UI issue.

**Comment by AnWeber** [comment]
The fields were missing in the JSON schema
