### ISSUE TITLE
Minor issue with parentheses in test names

### ISSUE THREAD

**Issue by alekdavis** [AnWeber/vscode-httpyac#315]
If you create a test name that ends with parenthesized text and then you change the name by removing parentheses by backspacing, the left parenthesis remains in the view until you restart VSCode. 

To duplicate, create a test with name  `# @name test (this and that)`
![image](https://github.com/user-attachments/assets/4dc82f3c-8e06-4b3f-9f2a-45462c3fd01d)

Then just use the backspace key to remove all parenthesized text including poth parentheses, but it will still show the left parenthesis in the Testing view:
![image](https://github.com/user-attachments/assets/cc0e125d-9a95-47bd-b801-82243e84c13c)

You will need to restart VSCode to have the Testing view show the updated name without the left parenthesis.

A really minor issue, but I once spent a few minutes messing with it and trying to understand what is going on.

**Comment by AnWeber** [comment]
That's a good one. I had a cache and the label was not updated on hits from the cache. But the cache usually didn't work because the name was included in the cache, except when only special characters were changed.
