### ISSUE TITLE
Various pain points

### ISSUE THREAD

**Issue by alekdavis** [AnWeber/vscode-httpyac#316]
After working with httpYac on several projects (testing various internal and external REST APIs) for a couple of months, I'd like to share a list of the common pain points in hope that some things can be improved and make an already great tool even better. These are grouped by importance.

### Conditionally enable/disable requests
There is an open issue for this one: https://github.com/AnWeber/vscode-httpyac/issues/297.

### Response window

The default option of creating a new response file for every request is annoying (you need to deal with all these open files), so I use a single response output file (in the default `appdata` project folder), but keeping it always open and in focus is a challenge. 

The response window reflect the response from the last completed request (which is good), but if a request fails for some reason (e.g. it could be caused by a syntax error in the test code), then it does not get updated and it may appear as if the request was successful. Some sort of label or title showing the timestamp of the request execution could be helpful here. It would also be handy if the response window cleared before each request and (ideally) showed error information if something went wrong in the code that prevented request from being executed. 

Also, if you close the response window, it may be a challenge to make it appear again. It normally gets visible when I run tests using codelens, but when I run tests from the Testing view, sometimes (but not always) the response window does not appear and there is no easy way to load it. It would be helpful if there were a **simple way to show/hide the response window** on the right side of the workspace (or whatever location is designated for it).

### Output/logs

Currently, there are three output logs for httpYac: console, log, and request. There are several usability issues with each and all of them.

First, the request output is self-explanatory, but it's not clear what goes to console and what goes to log (aren't all of them logs?). 

The most serious usability issue is that the output log entries keep growing without any visible marks between test runs and requests. At the very least, for the current functionality, it would be helpful to include some sort of **output header** (horizontal line, timestamp, etc.) at the beginning of each **test run** (and by test run, I mean an execution of a single or multiple tests). It would also help if output for **each request were also marked** (by test name). This will help to easily to find and cross reference request-specific log entries when running a batch (this could be controlled via a setting).

It would be even nicer if there were a setting to allow **clearing all httpYac outputs before each test run** (currently, I need to clear them all manually, which is a bit tedious). It could also be determined by a setting.

Another great feature (or an alternative to the above) would be a **combined log**. When I debug tests, I often need to switch between the output windows and if the test involves multiple requests, finding the corresponding records between various httpYac logs can be tricky. I really wish there were a single log combining the information from all three outputs (console, log, and request) in a single place. It would make debugging a bit easier.

I don't know if this is a VSCode behavior and there is a way to do anything about it, but every time I run a test (or multiple tests), the output tab switches to Test Results. I'm not sure what this tab is for (it does not show anything for me), but even if I switch to one of the httpYac output tabs, once I execute a request, the tab goes back to Test Results. If the Test Results tab could be used to show the combined outputs of all httpYac output windows, that would be perfect. I have a feeling it may not be possible, so another suggestion (and I'm also not sure if it is possible) would be to keep whatever output tab was active to stay in focus on each run, so the **focus would not auto switch to Test Results**. 

### Test dependency variables

Because of the response variable scoping (for the response variables referenced via `@ref`), I often need to reset the environment before executing tests. Ideally, I wish the `@ref` variables were cleared before each test run. 

Maybe have another reference tag, such as `@runRef` in addition to `@ref` and `@forceRef`. Or have a setting that would **reset the variables referenced via `@ref` before the test run** in which case the `@ref` link could be used. 

Also, the **scoping logic should be better documented** and hopefully extended because it is not very intuitive and is lacking a common behavior (resetting all variables before each test run). Until I got it explained in another thread on GitHub, I did not realize how it worked and made a few wrong assumptions (and spent several weeks trying to figure out why the tests did not always work).

### Certificate validation

Can **certificate validation be disabled by default**? A common scenario for a new user or a demo with someone would be to install the tools and then run some request against a local host or some test instance with a self-signed or fake cert and it always fails. Most developers disable cert validation for testing anyway, so it would be easier to set cert validation turned off as a default and turn it on via a configuration. Or maybe have it turned off for localhost, intranet, or some other reasonable host string (collection or regular expression).

### Code validation

If you mess up a project (and there are many ways to do this), it may not be obvious but bad things will happen. I once copied a file, changed some test but forgot to change test names, and the test names in the Testing menu were messed up (they retained one test that I deleted from the file and I could not figure out how to get rid of it until I gave all tests unique names). I'm not sure if this is possible, but it would be helpful if some **validation were done before the test run** and if basic errors (like duplicate test names) were found and error message would be displayed in a prominent place (Response tab?).

### Settings

**HttpYac: Environment selected on start**: It would make more sense to make it a project-specific setting since different projects may have different environment names. A logical place for the default environment setting would be the environment file that is part of the project (it can override the global setting), e.g. add a `$startup` element in addition to `$default` and `$shared`.

### Codelens
It would be nice to have a **code lens option to reset environment** in addition to the _Httpyac.reset environment_ command palette. Sometimes Httpyac.reset environment option does not appear in the command palette and it does not show up in auto-complete/drop-down (not sure why), so a codelens link would make it always available.

### Settings

_HttpYac: Codelens_ settings are confusing: The description says "_Specifies which codelens (items? options? features?) should be suppressed"_. So, will the checked options be suppressed or will the unchecked options be suppressed? And what does "suppressed" mean? I checked and unchecked such options as send and sendAll and I did not see any differences in the UI. 

### Canceling requests

If a request hangs (say, there is a network/proxy issue), there is no way to cancel it. The test result icon will keep showing the running request until you close the IDE. Is there a way to stop/cancel a running/hanging request?

### Environment

It would be handy to have a variable holding the current environment name. Use case: In our regression test, certain tests can only be run in specific environments, so I need to disable/enable them based on the active environment. I currently use a property that I define in each environment that I check but it would be more straightforward if I could use the current environment name in the pre-request code.

### IDE

Is there an option to permanently hide a test (common.http) in a project, so it does not appear in tests (since it does not have any tests and only contains common logic)? You can manually hide it but after a reload or checkout on a new system, it may still be visible.

**Comment by AnWeber** [comment]
I need time to process the input. I once started to improve the logging and use LogOutputChannel from vscode. And would also reset the channel before each request. Unfortunately a bug from vscode gets in the way (microsoft/vscode#224516).
On the subject of why I fill three OutputChannels. Log was intended for the entire log, Request I use so that I can see as original a display as possible of what I send to and receive from the server. Console was created later because users wanted a separate display for their own output. I now add the Console output back into Log, then it should be easy again.

**Comment by alekdavis** [comment]
Thanks, @AnWeber. Some of these may be due to my ignorance, so do not take all of them literally (maybe there is a way around some and I'm simply not aware).

**Comment by AnWeber** [comment]
All good. There are valid points and room to improve. Just difficult to answer in an orderly fashion due to the quantity.

**Comment by AnWeber** [comment]
> Is there an option to permanently hide a test (common.http) in a project, so it does not appear in tests (since it does not have any tests and only contains common logic)? You can manually hide it but after a reload or checkout on a new system, it may still be visible.

It would be possible to use special file extensions for valid tests. To do this, you can change the setting `httpyac.testItemExtensions`. Using metadata is too late. I try to load as much lazy as possible and the file content is really only parsed when it is necessary. A kind of testIgnore would also be possible, but should these tests then be actively prevented or just not displayed.

**Comment by AnWeber** [comment]
> It would be nice to have a code lens option to reset environment in addition to the Httpyac.reset environment command palette. Sometimes Httpyac.reset environment option does not appear in the command palette and it does not show up in auto-complete/drop-down (not sure why), so a codelens link would make it always available.

There is a codelens option to reset environment. Enable httpyac.codelens.resetEnvironment. This option is only visible in the Command Palette if an Http file is currently open. I didn't want to clutter up the Command Palette

**Comment by AnWeber** [comment]
> If a request hangs (say, there is a network/proxy issue), there is no way to cancel it. The test result icon will keep showing the running request until you close the IDE. Is there a way to stop/cancel a running/hanging request?

![stop_testrun](https://github.com/user-attachments/assets/ec150d3a-9295-4d50-9471-853a84943733)

In Test Explorer a cancel Test Run Button is available. The executed command is testing.cancelRun but this could not get triggered by command palette because it is not visible. But I don't know why the VSCode team hides the button so well.

**Comment by AnWeber** [comment]
> HttpYac: Codelens settings are confusing: The description says "Specifies which codelens (items? options? features?) should be suppressed". So, will the checked options be suppressed or will the unchecked options be suppressed? And what does "suppressed" mean? I checked and unchecked such options as send and sendAll and I did not see any differences in the UI.

Yes, I agree with you. However, the change does not have a direct effect. I can only change it the next time VSCode asks me for the CodeLens. Simply insert a line in the file if necessary.

**Comment by AnWeber** [comment]
> Is there an option to permanently hide a test (common.http) in a project, so it does not appear in tests (since it does not have any tests and only contains common logic)? You can manually hide it but after a reload or checkout on a new system, it may still be visible.

You can use setting `testItemExtensions`. Default value is http and rest. You can change extension to only http. and rename your `common.http` to `common.rest`

> If a request hangs (say, there is a network/proxy issue), there is no way to cancel it. The test result icon will keep showing the running request until you close the IDE. Is there a way to stop/cancel a running/hanging request?

canceling is supported, but there was a bug in test runs, which I fixed today. If there are still problems, please open a new ticket



I find the ticket difficult to work on because it contains so many individual points that I can't tick off one after the other. It would be nice if we could separate the outstanding points (if there are any left) into individual tickets.

**Comment by alekdavis** [comment]
Nice tip on separating `rest` from `http` files.

I think you have already addressed most, if not all, from my list, but I will go over them and and create separate issues for the ones that are still valid. I will close this issues. Many thanks.
