### ISSUE TITLE
Test results output contains wrong name of the skipped requests

### ISSUE THREAD

**Issue by alekdavis** [AnWeber/vscode-httpyac#319]
If a test is skipped, TEST RESULTS tab shows the message indicating that the test was skipped, but instead of the test/request/response name, it uses the hard coded value of  `skippedrequest`, e.g.:

![image](https://github.com/user-attachments/assets/21ede871-1d79-4a93-9c2c-401c5a727f30)

Instead of `Test skippedrequests is skipped`, it should say something like `Request is skipped` or `Tests are skipped` `Request 'Demo test Z' is skipped` or something like this (I think `Request is skipped` makes most sense, since it may have no tests associated with it). 

P.S. Love that this message is displayed in the TEST RESULTS and love the TEST RESULTS output. Now, instead of switching between various output logs, the TEST RESULTS output is the only output I check 90% of time (with exception of cases when I need to check responses for troubleshooting). Thanks a lot for this. Really handy.

**Comment by AnWeber** [comment]
Message already changed to `Test skipped`
<img width="464" alt="{CADB72DC-B74A-434D-904B-9741B9946F0E}" src="https://github.com/user-attachments/assets/884e2563-dae8-4ed3-bd87-54bb8ef62b2b">

**Comment by alekdavis** [comment]
I did notice. Looks good. Thank you.
