### ISSUE TITLE
Issues with stand-alone .http file

### ISSUE THREAD

**Issue by alekdavis** [AnWeber/vscode-httpyac#320]
I was doing a demo trying to demonstrate simplicity of httpYac and ran into a weird issue. So, I was trying to demonstrate the use of a single, standalone .http file (not a folder). It loads the file fine and I can run the tests using the CodeLens options, but when I try to open the Testing view or jump to it via the Reveal test in Explorer context menu, the test buttons in the source window disappear and no tests get displayed in the Testing window. 

https://github.com/user-attachments/assets/8652bd49-9f0e-41b0-9f60-01ee2cbe7f08

But there is a split second when the Testing window gets to display the tests before it switches to the message that additional extensions may be needed.

![image](https://github.com/user-attachments/assets/aad22733-1c2d-46ee-8d6f-d78851c7348a)

I also notice that when I try to load the same file (doing pretty much the same), sometimes the Testing menu would appear fine.

**Comment by AnWeber** [comment]
When I open the Test Runner, I first load all the test files. I use the entire current workspace for this. In this scenario, however, no workspace is open and previously discovered test cases are overwritten. I now use all visible files as a fallback in such a case.
