### ISSUE TITLE
Stopped tests show as successful

### ISSUE THREAD

**Issue by alekdavisintel** [AnWeber/vscode-httpyac#323]
If I run a long running test (say, I ran the request and I am debugging server code locally) and click the Cancel Test Run button (the rectangle thing next to the TESTING view header), the test icon shows as green check mark to indicate that the test was successful, while it was not (basically, the testy/request did not complete). 

![image](https://github.com/user-attachments/assets/74c143c8-1758-4b8a-875c-b9862e17766c)

Not a big deal, since when cancelling the run, one would know that it was not completed, but still.

**Comment by AnWeber** [comment]
cancelation of test run did not work correctly. I registered my cancellation logic on the token provided by the test api. but I needed to use token provided by test run object. I also forgot to add skipped test result if user canceled the executation.
