### ISSUE TITLE
Failed asserts show stack trace in httpyac - Request output

### ISSUE THREAD

**Issue by alekdavis** [AnWeber/vscode-httpyac#326]
I'm not sure if this is a configuration issue but I could not find anything. Wen an assertion fails (e.g. when I check HTTP response status using the simple `?? status == 200` syntax), the `httpyac - Request` output window displays the full stack trace for the failed assertions, e.g.: 

![image](https://github.com/user-attachments/assets/37082c82-340b-496a-b373-9c5c9d234fd2)

That's a lot of text with little, if any, value. Unless there is some sort of bug in code, I do not think anyone is interested in the full call stack of the assertion call. I just need to know if the assertion was successful or if it failed (and if it failed, then why). 

UPDATE: Also, on a similar topic, in the TEST RESULTS window, if the assertion fails, there is no stack trace, but the failed assertion message, still includes the extension source file and line, such as:

```console
✖ response.parsedBody.result.data == This (AssertionError [ERR_ASSERTION]: response.parsedBodyresult.data (That) == This - c:\Users\xxxxxx\.vscode\extensions\anweber.vscode-httpyac-6.15.1\dist\extension.js:177:36504)
```

I'm not sure how useful for the user, the source file of the extension would be. I think this version would be a bit easier to read:

```console
✖ response.parsedBody.result.data == This (AssertionError [ERR_ASSERTION]: response.parsedBodyresult.data (That) == This)
```

Or even shorter:

```console
✖ response.parsedBodyresult.data (That) == This
```

My take on this is that failed assertion conditions are expected, so as long as it is clear why the assertion failed, we're good. Now, if the assertion failed for some other reason (an internal bug or bad code), then, sure, give me all info (source file, line, etc), but if it failed just because the condition was not met, then that's as much as I need to know.

**Comment by AnWeber** [comment]
duplicate to #338
