### ISSUE TITLE
Failed test does not automatically cause the dependent test to fail

### ISSUE THREAD

**Issue by alekdavis** [AnWeber/vscode-httpyac#335]
I can't find the conversation, but I think I read that if test B references test A, and test A fails, test B should be automatically skipped (so no need to use the `$cancel` variable). It was not clarified what a failure means, but I assume that the test fails if (1) at least one of the assertions fails or (2) if the request call fails altogether. If my understanding is correct, then it does not seem to be the case. 

EXAMPLE:
```text
### Test X
# @name X
GET https://httpbin.org/json

?? status == 201

### Test Y
# @name Y
# #ref X
GET https://httpbin.org/anything

?? status == 200
```

RESULTS:
```text
---------------------

=== Test X ===

GET https://httpbin.org/json
=> 200 (379 ms, 607 B)
✖ status == 201 (AssertionError [ERR_ASSERTION]: status (200) == 201 - c:\Users\xxx\.vscode\extensions\anweber.vscode-httpyac-6.15.1\dist\extension.js:177:36504)

---------------------

=== Test Y ===

GET https://httpbin.org/anything
=> 200 (745 ms, 562 B)
✓ status == 200
```

P.S. While on the topic, is there a way to not print the ` - c:\Users\xxx\.vscode\extensions\anweber.vscode-httpyac-6.15.1\dist\extension.js:177:36504)` part on assertion failures?

**Comment by AnWeber** [comment]
@alekdavis Yes, I thought that ref were already skipped. But I didn't implement it correctly. Behavior now is that on error or when ref is skipped, the actual region is marked as skipped.

> P.S. While on the topic, is there a way to not print the  - c:\Users\xxx\.vscode\extensions\anweber.vscode-httpyac-6.15.1\dist\extension.js:177:36504) part on assertion failures?

I have now removed the file output if you use the ? syntax. When using the script notation, it should point to the respective code line, which makes sense in my eyes.

**Comment by AnWeber** [comment]
If testX fails, testY is not run, so it is skipped. This seems to be the best/ expected result after only runnig testY
<img width="444" alt="{AB27378F-C590-4F14-A136-B1ECB01CBC60}" src="https://github.com/user-attachments/assets/932f1a76-3986-4a6c-b968-66b2e8518403">

>> what is script notation

You can also write the tests in javascript. Using `??` should only remove some boilerplate and simplify the code
```
GET https://postman-echo.com/get

{{
  const { equal } = require('assert');
  test('status code 200', () => {
    equal(response.statusCode, 200);
  });
}}

```

**Comment by alekdavis** [comment]
@AnWeber I think you are doing far and beyond what could be expected, so thank you so much for being patient and replying to the questions. I really appreciate it. And please excuse me for posting often. I'm trying to get httpYac adopted across teams and need to understand a few things, so I can answer questions internally (I have a couple more I need to clarify, but I'll give a break for a few days ;-)).

Getting back to the original issues. I'm really sorry, but I still am confused. And even more than before. :-)

TEST DEPENDENCY

> If testX fails, testY is not run, so it is skipped. This seems to be the best/ expected result after only runnig testY

Are you saying that the behavior is different depending on whether testY is executed alone or as part of a batch? Regardless, I just tried and it does not seem to work like you say it should. Unless I am misunderstanding you. Just to clarify: you are saying that if testX fails, testY will be skipped, right? But it is NOT skipped. Here I run testY alone: 

![image](https://github.com/user-attachments/assets/7916c4d2-c8fa-4734-90b1-23b9f747273a)

Is the screenshot shows, it is NOT skipped. TestY is also NOT skipped when I execute the whole HTTP file (with two tests):

![image](https://github.com/user-attachments/assets/ee87963f-bf8b-48eb-ad35-00d128334ffa)

Am I totally misunderstanding what you are trying to explain because what I see is not what you seem to be claiming to happen. Are you saying that on your system testY is skipped? Because on mine, it is not, as you can see from the screenshots.

LINE NUMBER

> If you write your tests with javascript, it is helpful if you know which line in your tests fails.

I agree 100%. Except that (1) as you can see from the screenshot, the error message does not refer to my code, it refers to the source code of the extension, which is meaningless to me and (2) I am not even using JavaScript tests, I get the line number error from the `?? status` assertion.

**Comment by AnWeber** [comment]
I changed behaviour with v6.16. now it should get skipped

**Comment by alekdavis** [comment]
I just installed v6.16, but the behavior (for the skipping, or should I say NOT skipping) is still the same.
![image](https://github.com/user-attachments/assets/6e3cf86b-b10a-470a-8d01-cf5cfc4b965e)

![image](https://github.com/user-attachments/assets/39c34f0e-7462-420b-989f-2966800656bd)

I did notice that the error message no longer includes the extension file line number. Looks cleaner now. THANK YOU!

**Comment by AnWeber** [comment]
you have a typo at using ref

```
# @ref X
```
![set_skipped](https://github.com/user-attachments/assets/15fe334b-c61c-44a8-a4a7-e9baa825cb7f)

**Comment by alekdavis** [comment]
> you have a typo at using ref

Ah, right, got a wrong screenshot. But it still does not work with `@ref`. It does work with `@forceRef`, though, but I assume that both should work the same.


https://github.com/user-attachments/assets/c7f6ac77-49af-4081-946e-b1e600e45c81

**Comment by AnWeber** [comment]
Now I understand the problem. If I just run Y, it works correctly the first time. The second time it would no longer execute because of @ref X, since the X has already generated a response and this is now being used. That's why forceRef also works, because X is always executed again here.
The solution would be to delete the response variable again, or only set it if all TestResults were successful in the end.

Translated with DeepL.com (free version)
![works_on_first_request](https://github.com/user-attachments/assets/e988ba60-5faa-4119-acb5-d617a4a8c7dc)

**Comment by alekdavis** [comment]
OK, looks like v6.16.2 fixed it for `@ref``. Thank you!
