### ISSUE TITLE
Is there a way to reload the env files I selected last time?

### ISSUE THREAD

**Issue by dragondove** [AnWeber/vscode-httpyac#39]
Thanks for the great extension! I'm happy to use it.
There is a environmentSelectedOnStart option to select envs on startup. I wonder if there is a way to select the envs I selected last time before I colse the eiditor.

**Comment by AnWeber** [comment]
It will work with the next version. Just set the setting `httpyac.environmentStoreSelectedOnStart` to true. Default is intentionally set to false, I find it to be dangerous because the last system may be productive, but I wouldn't necessarily think about it the next time I start it.

**Comment by dragondove** [comment]
Ha, it's true most of us are forgetful, me too. But I won't add production environment to my envs since I have to permission to invoke productive apis. Thus this option is useful for me.

**Comment by AnWeber** [comment]
The change can be tested with release 2.12.5.

**Comment by dragondove** [comment]
Confirmed release 2.12.5 works as expected.

**Comment by AnWeber** [comment]
Thx
