### ISSUE TITLE
ReferenceError: sth is not defined

### ISSUE THREAD

**Issue by dragondove** [AnWeber/vscode-httpyac#40]
I've wrote sth like this:
```http
### regenerate invoice
@invoiceId = 21060216492001061854

PUT {{host}}/v1/electronicInvoice/regenerate?invoiceId={{invoiceId}}
```
the 'host' variable is defined in a env file, and I defined invoiceId in current region. When I attempt to send a http request, I got errors. The trace followings:
```log
ReferenceError: invoiceId is not defined
    at Object.userJS (d:\apis\gtc\einvoice.http:12:92)
    at Object.<anonymous> (c:\Users\jingc\.vscode-oss\extensions\anweber.vscode-httpyac-2.12.4\dist\extension.js:292:37177)
    at Generator.next (<anonymous>)
    at c:\Users\jingc\.vscode-oss\extensions\anweber.vscode-httpyac-2.12.4\dist\extension.js:292:36182
    at new Promise (<anonymous>)
    at s (c:\Users\jingc\.vscode-oss\extensions\anweber.vscode-httpyac-2.12.4\dist\extension.js:292:35927)
    at Object.g (c:\Users\jingc\.vscode-oss\extensions\anweber.vscode-httpyac-2.12.4\dist\extension.js:292:36461)
    at t.JavascriptVariableReplacer.<anonymous> (c:\Users\jingc\.vscode-oss\extensions\anweber.vscode-httpyac-2.12.4\dist\extension.js:292:140016)
    at Generator.next (<anonymous>)
    at s (c:\Users\jingc\.vscode-oss\extensions\anweber.vscode-httpyac-2.12.4\dist\extension.js:292:139204)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by AnWeber** [comment]
I could not reproduce the error right now. I guess the error also disappeared after reopening the file on your pc. Can you remember the order of the input. e.g. First RequestLine then Variable or the other way around?

**Comment by dragondove** [comment]
reopen file or restart vscodium doesn't solve the problem. I tried rewrite code with input variable first, and failed again.
Then I try with a new http file, it worked.
Now I know how to reproduce the error:
```http
### first req
GET http://sth/sth
### second
@sth = abc
GET http://sth/{{sth}}
```

**Comment by AnWeber** [comment]
I get the error now too. Interesting. I will have a look at it tonight.

**Comment by AnWeber** [comment]
Cause is the text in the delimiter `### second'. then the delimiter no longer works correctly
The following works
```
###
# @name second
```

**Comment by AnWeber** [comment]
The change can be tested with release 2.12.5.

**Comment by dragondove** [comment]
It's still broken. Even when I remove all text after delimiter
```http
###
@vara = 3
GET {{host}}/{{vara}} HTTP/1.1
###
@varb = 2
GET {{host}}/{{varb}} HTTP/1.1
```
the first variable `vara` works fine while `varb` does not.

**Comment by AnWeber** [comment]
Unfortunately, I won't get around to it today. I suspect it is the missing blank line between the first request and the ###. But that is just a guess.

**Comment by AnWeber** [comment]
error is as expected. The missing blank line between first request `GET {{host}}/{{vara}}` and the `###` is causing this. The outline view of vscode give a hint to the error. `@varb = 2` is added to request with vara.
![image](https://user-images.githubusercontent.com/13434739/120891733-6e73fd80-c60a-11eb-8a7a-dc3c5a770522.png)
Maybe I can optimize away the currently needed blank line. I will have a look at it

**Comment by AnWeber** [comment]
I have removed the required blank line. Now it is also possible to create the requests identically to Kibana. Nice:-)

**Comment by dragondove** [comment]
It works :)
Again, thanks for your work and patience on this project, hoping this project can be discovered by more people.

**Comment by AnWeber** [comment]
Thx for using my extension:-)
