### ISSUE TITLE
Feature Request: File scope variables

### ISSUE THREAD

**Issue by dragondove** [AnWeber/vscode-httpyac#45]
Hey, I'm using httpyac for a while. I wonder if there is a way to define variables in one http file.
Here is the outline from rest client with file scope variables:
![image](https://user-images.githubusercontent.com/24190403/123621056-6d1aa700-d83d-11eb-83ea-2573ac6ce216.png)

In httpyac, I got outline like this:
![image](https://user-images.githubusercontent.com/24190403/123621300-a3f0bd00-d83d-11eb-9673-1a5525a9d59c.png)

there is no variable va in the second request.

**Comment by AnWeber** [comment]
You have unfortunately found an error in the parser. A blank line after the variable corrects the outline. Unfortunately I didn't notice that, because I very much like to add blank lines for spacing. I will correct the parser.

**Comment by dragondove** [comment]
Thanks :)

**Comment by AnWeber** [comment]
The global variable was unfortunately detected as a non-empty region and not registered as a global region. With the next version this is fixed.

**Comment by AnWeber** [comment]
I have provided the new version:-)

**Comment by dragondove** [comment]
> 
> 
> I have provided the new version:-)

Tested, works fine.
