### ISSUE TITLE
Make timings & meta info easier to review

### ISSUE THREAD

**Issue by gerukin** [AnWeber/vscode-httpyac#49]
Both of those pieces of information are available (thank you), but are difficult to access for responses with large bodies. Currently, to review this, one has to open the request info pane and scroll past the response body (however long it might be).

### Suggestion
1. add `timing` and `meta` to hover preview,
2. and/or move them (and perhaps test results too for consistency) above the response body when opening the request info pane.

**Comment by AnWeber** [comment]
I would have made timings, testResults and meta more easily accessible. Do you think this is so good?
![image](https://user-images.githubusercontent.com/13434739/125172659-2d4bac00-e1bb-11eb-939f-e20f349910fc.png)

**Comment by gerukin** [comment]
I noticed it yesterday (well my yesterday anyway) thanks!

This works very well for me, and the total time is also shown above. Typically, besides the body, I care about the `status code`, `test summary`, `total time`, `content size` (all of which are shown at the top)...and will typically only look at the rest if one of the above bothers me. :)

**Comment by AnWeber** [comment]
Thx:-)
