### ISSUE TITLE
env files and variables are not correctly resolved

### ISSUE THREAD

**Issue by amkisko** [AnWeber/vscode-httpyac#51]
Hello!

Here's the list of few found issues related to dotenv feature:

1. For some reason env files with names like `.env.local`, `.env.production` are not properly handled, it is possible to select `.local` from the list, but variables are not available within script. In the same time `local.env` works fine.
<img width="476" alt="first_case_screenshot" src="https://user-images.githubusercontent.com/54796266/125401574-fe505880-e3bb-11eb-8216-a619a181d729.png">

```
# cat .env.local
TEST=this_is_a_test_value
```

Additional question: how to log all available variables?

2. Files within `env` directory is not visible in the list of available environments. Structure is:
```
|__specs
  |__env
    |__.env.local
    |__local.env
  |__requests.http
```

3. The editor shows variables from env as missing ones (red underline).
<img width="254" alt="third_case_screenshot" src="https://user-images.githubusercontent.com/54796266/125401477-e5e03e00-e3bb-11eb-8267-70d685854f7a.png">

Probably it will be good to have environment name to be set as a global variable, at least it gives an option to use dotenv-like packages.

Also at the moment it almost impossible to create Postman-like directory structure (or I could not figure out how):
```
|__specs
  |__env
    |__local.env
    |__staging.env
    |__production.env
  |__api
    |__user
      |__auth.http
      |__profile.http
    |__messages
      |__index.http
      |__create.http
      |__update.http
      |__destroy.http 
```

Configuration:
```
VSCodium
Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-11T00:18:10.593Z (2 days ago)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

httpYac - Rest Client
anweber.vscode-httpyac
anweber
v2.16.1

Httpyac: Dotenv Dirname = env
Httpyac: Dotenv Enabled = true
Httpyac: Dotenv Variable Provider Enabled = true
Httpyac: Environment Pick Many = true
```

**Comment by AnWeber** [comment]
1. Will have to look into it, I use the exact other spelling and it works for me. But for Linux the .env.local would be better.
2. Currently I only search the root folder of the workspace for the env folder. The change request with the folder structure is already addressed in #50. This can be corrected in the meantime with the setting `httpyac.dotenvDirname`.
3. The red underlining is your installed rest-client extension. It only resolves dotenv variable in the same root like the http file. I would recommend to use only httpyac or rest-client, not both, because we solve the same purpose differently.

**Comment by amkisko** [comment]
Thanks for the reply.

2. Tuning `httpyac.dotenvDirname` does not affect anything, I could not make it work, tried `./env` and `../env` and `env`.
3. Correct, I completely forgot about this extension (rest-client), disabling it helped.

**Comment by AnWeber** [comment]
What is your folder structure in vscode 
```
|__specs
  |__env
    |__...
  |__api
    |__...
```
or 
```
|__env
  |__...
|__api
  |__...
```
If `httpyac.logLevel` is set to trace, all search paths are written to output console `httpyac - Log`. You just need to reopen vscode or execute comman `httpyac.reset`

**Comment by amkisko** [comment]
Current folder structure is described in initial post under the second point, api specs are stored somewhere in deep structure of the project, no `env` directory in root.

```
|__specs
  |__env
    |__.env.local
    |__local.env
  |__requests.http
```

**Comment by AnWeber** [comment]
then you need to configure ./specs/env

**Comment by amkisko** [comment]
> then you need to configure ./specs/env

Yeah, and probably this should be stored inside `.vscode/settings.json` per project.

**Comment by amkisko** [comment]
Changing `httpyac.dotenvDirname` to `./specs/env` does not affect the list, still no entries from the directory.

Can extension also fire an exception if directory is not found?

**Comment by AnWeber** [comment]
I have now recreated your project. I could understand the error with .env.local, but not the problem with the env folder.
![env](https://user-images.githubusercontent.com/13434739/125439195-6a48c178-cf28-4fa2-b66f-46b12235ea42.gif)

my project as zip [#51.zip](https://github.com/AnWeber/vscode-httpyac/files/6808252/51.zip)

**Comment by AnWeber** [comment]
I have provided an update to vscode-httpyac (v2.20.0) that fixes the bug. I will continue to work on the problems with recognizing the env files using #50.
