### ISSUE TITLE
Default comment behavior incorrect in script blocks

### ISSUE THREAD

**Issue by gerukin** [AnWeber/vscode-httpyac#52]
In script blocks the editor shortcut for commenting things out behaves as if the line were http language instead of js.

### Expected
```
{{
  // highlight me, press the keyboard shortcut to comment out -> I was just commented out
}}
```

### Actual
```
{{
  # highlight me, press the keyboard shortcut to comment out -> I was just commented out as if I were http lang
}}
```

Syntax highlighting does work as expected however, including for comments (probably recognizes `//` as comment and `#` as itself).

**Comment by AnWeber** [comment]
The specification of the language for each section was not yet complete. However, I was able to copy the correct specification from vetur and function

**Comment by AnWeber** [comment]
I have provided an update to vscode-httpyac (v2.20.0) that fixes the bug.
