### ISSUE TITLE
Pretty Print only works on "httpyac.responseViewContent": "body"

### ISSUE THREAD

**Issue by AnWeber** [AnWeber/vscode-httpyac#56]
Pretty print is only working in responseViewContent `body`. `exchange` only formats body if json is used. Provider auto formatting for other types of body like. [rest-client](https://github.com/Huachao/vscode-restclient/blob/eead3c1ce5dec498ea96ac1fab8b0ac56bf83643/src/utils/responseFormatUtility.ts#L31) is using pretty-data for formatting.

### Discussed in https://github.com/AnWeber/vscode-httpyac/discussions/55

<div type='discussions-op-text'>

<sup>Originally posted by **chrismalek** July 20, 2021</sup>
Hello,

First thanks for all the work on this. This is really a stellar plugin. 

I have been watching httpyac closely. I used rest client all day everyday. However, I like some of the subtle features of httpyac and have been wanting to switch over..

I tried to make a switch today to httpyac but the pretty print only seems to work with this setting.

```json
{
"httpyac.responseViewContent": "body"
}

```

I prefer this setting when debugging APIs however the pretty print does not seem to work.  Is that a bug or a "feature"?

```json
{
"httpyac.responseViewContent": "exchange"
}

```</div>

**Comment by AnWeber** [comment]
fixed with bb2ef433b6d54b8337c0c52b4f65b3cf7e23ed8c.  For XML formatting currently [xml-formatter](https://www.npmjs.com/package/xml-formatter) is used.

**Comment by chrismalek** [comment]
Thanks I got it working. I was struggling because I was confused about this setting and I was reading it opposite.

For the pretty print to work this must be set.

` httpyac.responseViewPreserveFocus": true,`

**Comment by AnWeber** [comment]
Yes, you are right. But this is a copy paste bug. I will fix it in the next version.
