### ISSUE TITLE
How to Disable SSL Verification?

### ISSUE THREAD

**Issue by shenngw1127** [AnWeber/vscode-httpyac#57]
When i send the request by httpYac

```
GET https://172.16.18.215/v3/project/c-8tk2p:p-7p2kb/workloads
Authorization: Bearer token-yyyy:xxxxxx...
Accept: application/json
```

 Because that i have used a self issued certificate for inner https server, i got an error as below:

RequestError - unable to verify the first certificate => Disable SSL Verification could fix the problem (# @noRejectUnauthorized or use settings httpyac.requestGotOptions)

Please tell me how to set httpyac.requestGotOptions?
Thanks!

**Comment by AnWeber** [comment]
add this setting to your vscode settings:
```
"httpyac.requestGotOptions": {
        "request": {
            "https": {
                "rejectUnauthorized": false
            }
        }
    }
```
see Anweber/httpyac#39 for more information

**Comment by AnWeber** [comment]
if there are problems, just reopen issue. thx

**Comment by shenngw1127** [comment]
i just add flowing lines in my settings.json

```
    "httpyac.requestGotOptions": {
        "https": {
            "rejectUnauthorized": false
        },
        "request": {
            "https": {
                "rejectUnauthorized": false
            }
        }
    }
```

NO effect. show errors yet.

```
RequestError - unable to verify the first certificate => Disable SSL Verification could fix the problem (# @noRejectUnauthorized or use settings httpyac.requestGotOptions)
```

**Comment by AnWeber** [comment]
can you configure `httpyac.loglevel=trace` and send me content of outputchannel `httpyac - Log` 
Or does adding meta data noRejectUnauthorized fix problem?
```
# @noRejectUnauthorized
GET https://172.16.18.215/v3/project/c-8tk2p:p-7p2kb/workloads
Authorization: Bearer token-yyyy:xxxxxx...
Accept: application/json
```

**Comment by AnWeber** [comment]
I may have just found a mistake on my end. The output channel is not written. As an alternative you can use manual logging of the request. And I also do not get the expected output for the setting. I will have a closer look

**Comment by AnWeber** [comment]
I'm sorry, but I had a few errors in the last version. I focused more on the CMD support and didn't test that closely in the extension. Both the logging and the setting were faulty. But now it should work with this setting

```
"httpyac.requestGotOptions": {
        "https": {
            "rejectUnauthorized": false
        }
    }
```

**Comment by shenngw1127** [comment]
i just upgrade and tried. it was fixed.
Thanks!

**Comment by AnWeber** [comment]
thx for your response:-)
