### ISSUE TITLE
"Generate Code" not work.

### ISSUE THREAD

**Issue by stephsix** [AnWeber/vscode-httpyac#64]
extension version: v3.1.0
operating system: mac os
problem:
I clicked the "Generate Code" command in the right click popup menu, after choosing the target template(e.g. Shell - cURL), nothing happened except a quickly flashed process notify.

**Comment by AnWeber** [comment]
Thank you for reporting. Do you get an error message. This would appear in the output in the `httpyac - Log` tab. Would be great. Otherwise I will try it out myself.

**Comment by stephsix** [comment]
In my case, there is not any error message appear in the `httpyacc - Log` tab. 
I forked your great job and tried it locally with my Macbook Air, finding that there may be something wrong with the method "generateCodeRequest" in (src/provider/harCommandsController.ts):
![image](https://user-images.githubusercontent.com/23513086/132724374-cc5f0665-db23-44d8-9d33-4ba0bd9af2b0.png)
**It never hit my breakpoint on the callback of context.httpClient during "Generate Code"**.
FYI, here is my testing code:
```javascript
// gen_code_not_work.http
{{
    exports.date = "2021-09-10"
}}

GET https://httpbin.org/json HTTP/1.1
Date: {{date}}
```

**Comment by AnWeber** [comment]
This is exactly the right method. Probably the error is in httpyac, which does not use the httpClient correctly.
If you want to continue looking there, here's what you'd have to do.
1. `git clone`, `npm install` and `npm link` in httpyac folder
2. `npm link httpyac` in vscode-httpyac folder
3. modify`package.json` of httpyac (remove "types" and change "main" from dist to src)
```json
{
  "main": "./src/index.ts",
  "types2": "./dist/index.d.ts",
```
4. modify `tsconfig.json` in vscode-httpyac (add httpyac to rootDir)
```json
{
  "compilerOptions": {
     "rootDirs": ["src", "./node_modules/httpyac/src"],
  }
}
```
5. `npm run watch` in vscode-httpyac 

After these changes, when vscode-httpyac is started, the httpyac source can also be debugged.

You don't necessarily have to find the bug. I'll be happy to take a look at it though, I'd just check out the support for GRPC before I do that.

**Comment by AnWeber** [comment]
The cause was that the [httpClient was overwritten](https://github.com/AnWeber/httpyac/blob/main/src/utils/httpRegionUtils.ts#L86) in the api. I took the opportunity and rewrote the logic to use `logResponse` interface. With version 3.2.0 the call should work correctly again
