### ISSUE TITLE
input box closes on vscode losing focus

### ISSUE THREAD

**Issue by hariprasadiit** [AnWeber/vscode-httpyac#69]
Thanks for the awesome extension and library.

I've found that input box closes if the focus is lost. I think in most of the cases either user enters the value or may want to copy paste the value. This behaviour is not ideal for the copy/paste case.

I think it's better to wait for the user to close the input box explicitly.

We can achieve this by passing `ignoreFocusOut?: boolean;` flag to the vscode's inputbox

**Comment by AnWeber** [comment]
I overlooked the setting. I will also include it in the Quickpick dialog.

**Comment by hariprasadiit** [comment]
sure. QuickPick is being used in couple of places. Would it make sense to persist it in all the places?

**Comment by AnWeber** [comment]
Probably yes. I have often closed it conciliatory.
