### ISSUE TITLE
Problem with oauth variables

### ISSUE THREAD

**Issue by asherber** [AnWeber/vscode-httpyac#72]
I'm using oauth2 with a service that requires an extra header with the request (not with the token request, with the actual data request).

```
@oauth2_clientId = mdfsflsmklf
@oauth2_clientSecret = sdlfmsdklfm
@oauth2_tokenEndpoint = https://www.example.com/v1/token
@oauth2_scope = some-api

GET https://othersite.com/data
client-id: {{oauth2_clientId}}
Authorization: oauth2
```

The oauth2 request works just fine and gets a token. But the data request does not replace the indicated variable and sends the header as `client-id: {{oauth2_clientId}}`

The same thing happens if I use some prefix other than `oauth2`. In order for this to work, I need to add another variable which duplicates the value of `oauth2_clientId`.

**Comment by AnWeber** [comment]
Thanks for usingy extension:-)
