### ISSUE TITLE
Client SSL certs

### ISSUE THREAD

**Issue by asherber** [AnWeber/vscode-httpyac#73]
I know that I can use `clientCertificates` to specify SSL certs on a per-site basis.

```json
{
    "clientCertificates": {
        "mysite.com": {
            "passphrase": "dmfsklmfml",
            "pfx": "c:/mycert.pfx"
        }
    }
}
```

I have one .http file for which I'd like to use the same cert for all requests, regardless of site. Looking at the docs, I thought that this would work:

```json
{
    "request": {
        "https": {
            "passphrase": "dmfsklmfml",
            "pfx": "c:/mycert.pfx"
        }
    }
}
```

But when I do that and send a request, the request never returns -- no error, but the notification indicating that a request is in process just stays there until I cancel it.

Am I doing something wrong, or misunderstanding the usage?

**Comment by AnWeber** [comment]
Actually, I would have already tried to mention that each host must be explicitly [mentioned](https://httpyac.github.io/guide/variables.html#ssl-client-certificate):-)
The host is passed as the [property name of clientCertificates](https://github.com/AnWeber/httpyac/blob/main/src/variables/replacer/clientCertVariableReplacer.ts#L17). Currently there is no logic that expects a * or similar.
I don't currently have this use case myself and therefore no experience with clientCertificates, so I'm open to suggestions.
