### ISSUE TITLE
Feature request: Better visibility of environment

### ISSUE THREAD

**Issue by asherber** [AnWeber/vscode-httpyac#79]
It would be nice if the current environment were more visible than in the CodeLens at the top of the file. 

I often have multiple requests in a file, and if I've scrolled down to one lower in the file, the name of the current file is not visible; I have to scroll to the top to check it and change it if needed. Even with just a single request in a file, the fact that CodeLens text is smaller and lighter makes it hard to see.

Being able to see and change this value from someplace like the status bar would be helpful.

**Comment by AnWeber** [comment]
Actually yes, but somehow it didn't work out. Comes with the next update
