### ISSUE TITLE
Incorrect result document type inferred

### ISSUE THREAD

**Issue by asherber** [AnWeber/vscode-httpyac#87]
It seems like httpyac is not always using the content type of responses, which means that the responses are not pretty printed correctly.

*   If I call an endpoint /foo which returns json (content type application/json), the response is correctly formatted. I can see from the breadcrumb that the file is named xxx.json (where xxx is the name of the request -- ### xxx)
*   If I call an endpoint /foo.svc which returns content type text/xml, the response file is named xxx.svc and is not formatted as XML; vscode has Plain Text as the language
*   If I call an endpoint /foo which returns content type application/soap+xml, the response file is actually named foo.**json** with language type JSON.

Can the extension be smarter about determining the type of the response, so that vscode formats it correctly?

**Comment by AnWeber** [comment]
With the setting `files.associations` you could change the used language to VSCode: https://code.visualstudio.com/docs/languages/identifiers

But I will add a config setting to prefer mimetype over extension.

**Comment by asherber** [comment]
Note my third bullet point at top: An XML response gets a file with an extension of .json, so changing the vscode file association wouldn't help me here.

**Comment by AnWeber** [comment]
> Is there a reason that the map doesn't work with open?

VSCode does not allow to open Untitled Documents in Preview Mode. To use the [vscode.openWith command](https://code.visualstudio.com/api/references/commands), I must also have a correct Resource/ Uri.  After adding the history, it was easier to save all documents directly. With this step, the setting `responseViewLanguageMap ` is only used when I can't write to disk or in mode `reuse`.  
https://github.com/AnWeber/vscode-httpyac/blob/main/src/view/editorResponseHandler.ts#L50

> Could the extension by default know about some more basic content types without my having to explicitly add them to the map?

I use [mime-types](https://www.npmjs.com/package/mime-types) to determine extension by mimetype. For determining language id, I use some custom logic: https://github.com/AnWeber/vscode-httpyac/blob/main/src/view/editorResponseHandler.ts#L119-L147
And you can always expand anything if it makes sense. Just give me hints.

**Comment by asherber** [comment]
Shouldn't [this one](https://github.com/AnWeber/vscode-httpyac/blob/711bf83407c4378a38df1a4404e7c2452a7dc3b8/src/view/editorResponseHandler.ts#L134) be XML?

**Comment by AnWeber** [comment]
> If I call an endpoint /foo which returns content type application/soap+xml, the response file is actually named foo.json with language type JSON.

`application/soap+xml` has no extension in [mime-db](https://github.com/jshttp/mime-db/blob/master/db.json#L15269) (used by mime-types). I will extend it with the LanguageId logic if no extension could be determined using extension and mimetype.

**Comment by AnWeber** [comment]
> Shouldn't this one be XML?

XML in my use cases is not formatted and the VSCode html formatter can also format XML. That's why I preferred Html here.

**Comment by AnWeber** [comment]
I have provided the changes with v4.7.0. Please test. Thanks.

**Comment by asherber** [comment]
Thanks, this seems to work well for my use cases. 

The only thing that looks odd to me is that vscode seems to be expecting an array for `responseViewExtensionRecognition`. The settings UI tells me I have to edit in settings.json. When I add the setting there, I'm given a choice of `extension`, `mimetype`, or `regex` (?), and when I pick one I get an orange squiggly that says an array is expected.

I don't develop vscode extensions, but the code you added in package.json and config.ts looks to me like it's only expecting a string. Not sure what's going on here.

**Comment by AnWeber** [comment]
I tried 2 solutions: Setting as string array with the order or setting with the top priority. And ended up committing a half stand. Is fixed with the next release

**Comment by asherber** [comment]
Oh, I was looking at the 4.7.0 commit, didn't see that this changed in 4.7.1.

**Comment by AnWeber** [comment]
I just released a new version with the fix for the confiugration bug. Thanks again
