### ISSUE TITLE
GRPC includeDirs problem

### ISSUE THREAD

**Issue by lantian** [AnWeber/vscode-httpyac#88]
Hello,

There is a problem of relative path resolution for includeDirs option of GRPC. 

I have project in /home/user/work/project1 (linux path) opened in vscode.
In this project i have folder "packages", which contains a lot of proto, example tree:

```
packages
├── package1
│   ├── some1
│   │   ├── some1.proto
│   │   └── some1_service.proto
│   └── package.json
├── package2
│   ├── entity.proto
│   ├── package.json
│   └── property.proto
├── package3
│   ├── some2_service.proto
│   └── package.json
└── grpc-list.http            <--- this is file, which I use to call grpc, listed bellow
```

And file grpc-list.http: 
```
proto < ./package1/some1/some1_service.proto
includeDirs: ["./"]

GRPC {{host}}/.../List
{}
```

File ./package1/some1/some1_service.proto contains import like: `import package1/some1/some1.proto`

When i execute it, i got an exception:
```
ERROR: ExecuteHook: protoImport failed
ERROR: Error - ENOENT: no such file or directory, open '/home/user/work/project1/packages/package1/some1/package1/some1/some1.proto'
Error: ENOENT: no such file or directory, open '/home/user/work/project1/packages/package1/some1/package1/some1/some1.proto'
```

If i try to change includeDirs to "/home/user/work/project1/packages" or "./work/project1/packages" - it will work. But that's quit not an variant coz this is under version control and used by different developers =). It looks like it starts resolving of relative path from the HOME_DIR of the current user instead of project root folder.

**Comment by AnWeber** [comment]
Behavior has already been reported with [AnWeber/httpyac#75. ](https://github.com/AnWeber/httpyac/issues/75#issuecomment-932938370). I pass `includeDirs` directly into [@grpc/proto-loader](https://github.com/AnWeber/httpyac/blob/main/src/parser/protoHttpRegionParser.ts#L80-L84). Issue https://github.com/grpc/grpc-node/issues/1278#issuecomment-592086673 mentions that includeDirs should be absolute paths. Maybe you need to make an issue in @grpc/proto-loader ([these lines need to be changed](https://github.com/grpc/grpc-node/blob/master/packages/proto-loader/src/util.ts#L29-L37)).
It is possible to simply workaround issue with javascript. The options are already treated as a javascript, therefore the current folder can just be inserted with `__dirname`.

```
proto < ./package1/some1/some1_service.proto
includeDirs: [`${__dirname}`]

GRPC {{host}}/.../List
{}
```

**Comment by lantian** [comment]
Uh, thank you so much, I'm was not able to google it correctly, sorry. Closing here.

**Comment by AnWeber** [comment]
You are welcome. Glad it works for you. Thanks for using my project:-)
