### ISSUE TITLE
Support for IntelliJ-style http-client.env.json environment files

### ISSUE THREAD

**Issue by daedal-knickerbockers** [AnWeber/vscode-httpyac#9]
httpyac supports the .http files used by the IntelliJ HTTP Client, however, it does not support the IntelliJ way of defining environments. Being able to use a `http-client.env.json` file for environments would be great for cross IDE compatibility.

Example `http-client.env.json` file
```json
{
  "dev": {
    "host": "https://myhost.dev"
  },
  "qa": {
    "host": "https://myhost.qa"
  },
  "prod": {
    "host": "https://myhost.prod"
  }
}
```

The example file above should be parsed into three distinct environments named `dev`, `qa` and `prod`.

Is this a feature you also would like to support? If you need support on development, I'll gladly offer some 👍

**Comment by AnWeber** [comment]
thanks for using my extension. 
In which folder is the file located (root, same as http file, vscode setting?). The documentation of intellij is not really helpful ([Docs](https://www.jetbrains.com/help/idea/exploring-http-syntax.html#example-working-with-environment-files)). Do you have a example of a private env.json?
Thanks for your help, my license for Idea has expired.

**Comment by daedal-knickerbockers** [comment]
I tested in Webstorm instead of IntelliJ, but it should behave the same way as the base of the IDE should be quite similar.

The `http-client.env.json` file will be picked up from anywhere in the project folder structure. You can also have multiple files in different folders.
There is an error message when duplicate environment names are found between multiple files.

The `private` files will be excluded from version control by default and will append its properties to environments defined in `non-private` files.

`http-client.env.json`
```json
{
  "dev": {
    "host": "https://myhost.dev"
  }
}
```

`http-client.private.env.json`
```json
{
  "dev": {
    "auth": "****"
  }
}
```

In the .http file, you can access variables from both private and non-private files:
`myExampleRequest.http`
```http
POST {{host}}/foo
Authentication: {{auth}}
Content-Type: application/json

{
  "foo": "bar"
}
```

**Comment by AnWeber** [comment]
http-client.env.json/ http-client.private.env.json should be loaded now. These are searched either in the root or in a configurable folder (default is empty). could you please test it and report problems. thanks

**Comment by AnWeber** [comment]
maybe you should enable httpyac.intellijVariableProviderEnabled if your env.json files is next to the *.http file. See [readme](https://github.com/AnWeber/vscode-httpyac/blob/master/README.md)

**Comment by daedal-knickerbockers** [comment]
Thanks a lot for the fast implementation! 😮 👍 

I created a small test project and unfortunately, the variables in the environment do not seem to be picked up:

![image](https://user-images.githubusercontent.com/13169906/106642631-e5c85080-6588-11eb-8be2-f90c9a03baa0.png)

When selecting the environment, `dev` is available in the dropdown menu, but inside the .http file editor none of the variables can be resolved.

![image](https://user-images.githubusercontent.com/13169906/106642840-26c06500-6589-11eb-864d-d833166fcf73.png)

Trying to send the request results in an error:

![image](https://user-images.githubusercontent.com/13169906/106642795-19a37600-6589-11eb-8067-1dd1f08cbe6c.png)

Are there any debug logs with further information that might help you?

**Comment by AnWeber** [comment]
httpyac register a output panel. In every call the variables are logged.
But why is the host variable
set to https://127.0.0.1 or 127.0.0.1:443. Do you use other settings, like
vscode setting httpyac.environmentVariables? I would expect a
ReferenceError, if variable is  not defined, but it is a timeout. Or is a
proxy configured?



Daniel Kneip <notifications@github.com> schrieb am Di., 2. Feb. 2021, 19:03:

**Comment by AnWeber** [comment]
You did use the CodeLens "Send Request" to initiate the call. This is the code lens of [vscode-restclient](https://github.com/Huachao/vscode-restclient). 
![image](https://user-images.githubusercontent.com/13434739/106648585-c2090880-6590-11eb-961c-7912a3b3402f.png)
You need to use Code Lens "send"
![image](https://user-images.githubusercontent.com/13434739/106648135-29728880-6590-11eb-8097-4c7526c3a6c9.png)

I would recommend using only either vscode-restclient or my extension, not both. Because both extensions do more or less the same. I created my own extension, because my [pull request](https://github.com/Huachao/vscode-restclient/pull/674) got not integrated in vscode-restclient. So I created my own extension. In vscode-restclient is a [feature request](https://github.com/Huachao/vscode-restclient/issues/627) implementing intellij support, but I would not expect any progress.

**Comment by daedal-knickerbockers** [comment]
Oh boy, sorry, I totally forgot that I also hab REST Client installed.

Uninstalled it and tried again, now env resolution works just fine! 😃 

![image](https://user-images.githubusercontent.com/13169906/106724947-1cde4680-6609-11eb-8828-a6a3caaa401e.png)

However, actually sending the request produces an error:

```
[ERROR - 10:16:27] POST {{host}}/foo
Content-Type: application/json
Authorization: {{auth}}

{
    "foo": "bar"
}
[object Object]
TypeError [ERR_INVALID_URL]: Invalid URL: POST%20https://google.com/foo%0AContent-Type:%20application/json%0AAuthorization:%20BASIC%20****%0A%0A%7B%0A%20%20%20%20%22foo%22:%20%22bar%22%0A%7D
[ERROR - 10:16:27] requestCommandsController.send
TypeError [ERR_INVALID_URL]: Invalid URL: POST%20https://google.com/foo%0AContent-Type:%20application/json%0AAuthorization:%20BASIC%20****%0A%0A%7B%0A%20%20%20%20%22foo%22:%20%22bar%22%0A%7D
```

Looks like the URL gets appended with the headers? Is there a problem with my request syntax that I'm just missing?

**Comment by AnWeber** [comment]
there is an error in parsing your http file. 
```

**Comment by AnWeber** [comment]
if you are using another line carriage as the default of your operating system, this error happens.

**Comment by AnWeber** [comment]
![error](https://user-images.githubusercontent.com/13434739/106772285-233be500-6640-11eb-8abe-49a39bd70938.gif)

**Comment by daedal-knickerbockers** [comment]
Man, what a nasty thing ^^ It's working fine now 👍 

Variables from the `http-client.env.json` and `http-client.private.env.json` get picked up.
I also tested with some *real* requests we are currently using from Webstorm / IntelliJ, this works flawless too!

So looks good to me, besides the line feed problem 😃 

Is this something you would also address? In our case, most of the guys are using `LF` as they develop on unix-based machines, so the Windows guys also use `LF` instead of the native `CRLF`.

**Comment by AnWeber** [comment]
if you use the same line carriage as your os all is fine. but if you switch like LF on win or CRLF on linux you got the trouble. I already fixed it in my dev environment. I will release a fix later. I have to cook for my kids now.

**Comment by daedal-knickerbockers** [comment]
Thanks a lot Andreas! 🙇‍♂️

**Comment by AnWeber** [comment]
I pushed the fix to vsce. Would be nice if you could test it again.

**Comment by daedal-knickerbockers** [comment]
I just tested and it now works on both `LF` and `CRLF` on Windows 😃 

Thanks for the quick responses everytime!

**Comment by AnWeber** [comment]
You're welcome. Thanks for using my fun coding project😃
