### ISSUE TITLE
Variables cannot contain "-"

### ISSUE THREAD

**Issue by jg-cantaa** [AnWeber/vscode-httpyac#95]
![Screenshot_2021-12-14_13-36-02](https://user-images.githubusercontent.com/95756912/145999541-7aa74e2a-f1b5-4876-9d80-383c3ce0f490.png)
[Zipped Project](https://github.com/AnWeber/vscode-httpyac/files/7711642/specs.zip)

**Comment by AnWeber** [comment]
I am not a fan of this feature, but Intellij supports variables with `-`. For me this currently does not work, because I use Javascript for the variable determination. But since hyphens are not allowed in variables, this is problematic.

**Comment by AnWeber** [comment]
fix is released with v4.8.2. Thanks:-)
