### ISSUE TITLE
How to delete cached responses (reset global context)

### ISSUE THREAD

**Issue by rngtng** [AnWeber/vscode-httpyac#96]
In my scenario I connect multiple requests with re-using the value of the response. @ref works great here, especially with the local caching.  But now I want to delete the cache and delete any save responses. @forceRef would work but then in loose the cache feature. I found options To reset env or delete http responses but none do the trick…

**Comment by AnWeber** [comment]
I save the response in the variables. If the [variable already exists, the `@ref` does not trigger the request anymore](https://github.com/AnWeber/httpyac/blob/main/src/actions/refMetaAction.ts#L27). I thought command `httpyac.reset` would also reset the variables, but it is not so (bug). The easiest thing is to close all http files and reopen them. You can also overwrite the variable with false.

**Comment by rngtng** [comment]
Thanks the quick fix. What helper function you have in mind? For codelens?

**Comment by AnWeber** [comment]
Currently, once created variables cannot be deleted again using Javascript (`{{...}}}`) Just a `delete this["foo"]` would not work. I have a [utils method](https://github.com/AnWeber/httpyac/blob/main/src/utils/variableUtils.ts#L75), but it is not easily accessible. 
VSCode could also be extended to delete the set variables individually Similar to the userSessions. Let's see.

**Comment by AnWeber** [comment]
`reset` fix is released with v4.8.2.

**Comment by AnWeber** [comment]
I have now added the possibility to delete individual variables via script.
```
@foo=bar
{{
  delete this.foo
}}
###
GET https://httpbin.org/json?foo={{foo}} HTTP/1.1
```

**Comment by rngtng** [comment]
Sorry didn’t give feedback here. It’s indeed fixed. Thanks a lot!!
