### ISSUE TITLE
Env selector is missing $default

### ISSUE THREAD

**Issue by rngtng** [AnWeber/vscode-httpyac#97]
The new $default env works great, but the env selector needs an update too. Once Switched to a non default env I only can switch back by typing $default. A dedicated select option would be more convenient. Thx

**Comment by AnWeber** [comment]
Just press `ESC` but option `NONE` would be useful

**Comment by rngtng** [comment]
You‘re fast. Thanks the fix

**Comment by AnWeber** [comment]
feature is released with v4.8.2
