### ISSUE TITLE
An explanation on response body variables.

### ISSUE THREAD

**Issue by jg-cantaa** [AnWeber/vscode-httpyac#99]
Hi,
I would like to know how to access the response of the previous request as a variable.

Say I have this example: 
```
### test
# @name test
GET http://xkcd.com/info.0.json

### get image
GET {{test.response.parsedBody.json.img}}
```

The test request returns : 
```
{
  "month": "1",
  "num": 2566,
  "link": "",
  "year": "2022",
  "news": "",
  "safe_title": "Decorative Constants",
  "transcript": "",
  "alt": "Arguably, the '1/2' in the drag equation is purely decorative, since drag coefficients are already unitless and could just as easily be half as big. Some derivations give more justification for the extra 1/2 than others, but one textbook just calls it 'a traditional tribute to Euler and Bernoulli.'",
  "img": "https://imgs.xkcd.com/comics/decorative_constants.png",
  "title": "Decorative Constants",
  "day": "10"
}
```

After reading [these examples](https://github.com/AnWeber/vscode-httpyac/issues/59#issuecomment-888816302) I would expect the second GET request to get the image.

I could not seem to find Documentation on this specifically, just the [Scripting Section in the Docs](https://httpyac.github.io/guide/scripting.html#access-to-variables) which mentions the response to be accessible, but does not provide examples.

In the example above it does not replace the `{{test.response.parsedBody.json.img}}` and I have yet to find a way to actually get it o evaluate. It then just says `ERR_INVALID_URL` and shows  `{{test.response.parsedBody.json.img}}` as the URL.

It would be great if you could clarify how this feature works and document it for future users.

**Comment by AnWeber** [comment]
I still need to improve the documentation, but I would have already tried to describe it and also with examples
```
### test
# @name test
GET http://xkcd.com/info.0.json

### get image
# @ref test
GET {{test.img}}
```

You have several possibilities to access the request. The previous request is always `response`. But for this a request must be executed manually before. With `@ref` you can explicitly refer to other requests, which will be called automatically ([see](https://httpyac.github.io/guide/metaData.html#ref-and-forceref)). The body of the referenced request is provided as a variable with the name of the referenced request (in example test).

**Comment by jg-cantaa** [comment]
> The previous request is always `response`.

So like this? 
```
### get repositories
# @ref test
GET {{response.img}}
```

**Comment by AnWeber** [comment]
I thought yes, but it just didn't work out the way I wanted. With `SendAll` it does work. WIth only `Send` it doesn`t. But I would have said that it goes in both cases

```

GET http://xkcd.com/info.0.json

{{
  console.info(response.parsedBody.img)
}}

###
GET {{response.parsedBody.img}}
```

**Comment by AnWeber** [comment]
Now I know again. The reason was an out of memory, because all requests are stored in memory. For this reason I have removed the feature. Only within a call it is currently possible. That's why I can't actually put it back in and instead prefer to recommend the way with `@ref`.

**Comment by AnWeber** [comment]
With the new release, the response between calls is cached again.
